#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define BOOKERLY_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_12_regular.h",
  "./bookerly_12_bold.h",
  "./bookerly_12_bolditalic.h",
  "./bookerly_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_14_regular.h",
  "./bookerly_14_bold.h",
  "./bookerly_14_bolditalic.h",
  "./bookerly_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_16_regular.h",
  "./bookerly_16_bold.h",
  "./bookerly_16_bolditalic.h",
  "./bookerly_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOOKERLY_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bookerly_18_regular.h",
  "./bookerly_18_bold.h",
  "./bookerly_18_bolditalic.h",
  "./bookerly_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEXEND_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_12_regular.h",
  "./lexend_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEXEND_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_14_regular.h",
  "./lexend_14_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEXEND_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_16_regular.h",
  "./lexend_16_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEXEND_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./lexend_18_regular.h",
  "./lexend_18_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOKERLAM_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bokerlam_12_regular.h",
  "./bokerlam_12_bold.h",
  "./bokerlam_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOKERLAM_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bokerlam_14_regular.h",
  "./bokerlam_14_bold.h",
  "./bokerlam_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOKERLAM_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bokerlam_16_regular.h",
  "./bokerlam_16_bold.h",
  "./bokerlam_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define BOKERLAM_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bokerlam_18_regular.h",
  "./bokerlam_18_bold.h",
  "./bokerlam_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bokerlam_12_regular.h",
  "./bokerlam_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./bokerlam_12_regular.h",
  "./bokerlam_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
