#include "I18nStrings.h"

// THIS FILE IS AUTO-GENERATED BY gen_i18n.py. DO NOT EDIT.

// Language display names
const char* const LANGUAGE_NAMES[] = {
    "English",
    "Ti\xE1"
    "\xBA"
    "\xBF"
    "ng Vi\xE1"
    "\xBB"
    "\x87"
    "t",
};

// Character sets for each language
const char* const CHARACTER_SETS[] = {
    " !\"%&'()*+,-./012345689:<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]abcdefghijklmnopqrstuvwxyz|~\xC2"
    "\xAB"
    "\xC2"
    "\xB0"
    "",  // English
    " !\"%&'()*+,-./0123456789:<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]abcdefghiklmnopqrstuvwxyz|~\xC2"
    "\xAB"
    "\xC2"
    "\xB0"
    "\xC3"
    "\x80"
    "\xC3"
    "\x81"
    "\xC3"
    "\x82"
    "\xC3"
    "\x83"
    "\xC3"
    "\x8A"
    "\xC3"
    "\x93"
    "\xC3"
    "\x94"
    "\xC3"
    "\xA0"
    "\xC3"
    "\xA1"
    "\xC3"
    "\xA2"
    "\xC3"
    "\xA3"
    "\xC3"
    "\xA8"
    "\xC3"
    "\xA9"
    "\xC3"
    "\xAA"
    "\xC3"
    "\xAC"
    "\xC3"
    "\xAD"
    "\xC3"
    "\xB2"
    "\xC3"
    "\xB3"
    "\xC3"
    "\xB4"
    "\xC3"
    "\xB9"
    "\xC3"
    "\xBA"
    "\xC3"
    "\xBD"
    "\xC4"
    "\x82"
    "\xC4"
    "\x83"
    "\xC4"
    "\x90"
    "\xC4"
    "\x91"
    "\xC6"
    "\xA1"
    "\xC6"
    "\xB0"
    "\xE1"
    "\xBA"
    "\xA0"
    "\xE1"
    "\xBA"
    "\xA1"
    "\xE1"
    "\xBA"
    "\xA2"
    "\xE1"
    "\xBA"
    "\xA3"
    "\xE1"
    "\xBA"
    "\xA4"
    "\xE1"
    "\xBA"
    "\xA5"
    "\xE1"
    "\xBA"
    "\xA6"
    "\xE1"
    "\xBA"
    "\xA7"
    "\xE1"
    "\xBA"
    "\xA8"
    "\xE1"
    "\xBA"
    "\xA9"
    "\xE1"
    "\xBA"
    "\xAB"
    "\xE1"
    "\xBA"
    "\xAC"
    "\xE1"
    "\xBA"
    "\xAD"
    "\xE1"
    "\xBA"
    "\xAE"
    "\xE1"
    "\xBA"
    "\xAF"
    "\xE1"
    "\xBA"
    "\xB1"
    "\xE1"
    "\xBA"
    "\xB4"
    "\xE1"
    "\xBA"
    "\xB5"
    "\xE1"
    "\xBA"
    "\xB7"
    "\xE1"
    "\xBA"
    "\xB9"
    "\xE1"
    "\xBA"
    "\xBB"
    "\xE1"
    "\xBA"
    "\xBD"
    "\xE1"
    "\xBA"
    "\xBF"
    "\xE1"
    "\xBB"
    "\x81"
    "\xE1"
    "\xBB"
    "\x83"
    "\xE1"
    "\xBB"
    "\x85"
    "\xE1"
    "\xBB"
    "\x87"
    "\xE1"
    "\xBB"
    "\x88"
    "\xE1"
    "\xBB"
    "\x89"
    "\xE1"
    "\xBB"
    "\x8B"
    "\xE1"
    "\xBB"
    "\x8C"
    "\xE1"
    "\xBB"
    "\x8D"
    "\xE1"
    "\xBB"
    "\x8F"
    "\xE1"
    "\xBB"
    "\x91"
    "\xE1"
    "\xBB"
    "\x93"
    "\xE1"
    "\xBB"
    "\x94"
    "\xE1"
    "\xBB"
    "\x95"
    "\xE1"
    "\xBB"
    "\x97"
    "\xE1"
    "\xBB"
    "\x98"
    "\xE1"
    "\xBB"
    "\x99"
    "\xE1"
    "\xBB"
    "\x9B"
    "\xE1"
    "\xBB"
    "\x9D"
    "\xE1"
    "\xBB"
    "\x9E"
    "\xE1"
    "\xBB"
    "\x9F"
    "\xE1"
    "\xBB"
    "\xA1"
    "\xE1"
    "\xBB"
    "\xA3"
    "\xE1"
    "\xBB"
    "\xA5"
    "\xE1"
    "\xBB"
    "\xA6"
    "\xE1"
    "\xBB"
    "\xA7"
    "\xE1"
    "\xBB"
    "\xA8"
    "\xE1"
    "\xBB"
    "\xA9"
    "\xE1"
    "\xBB"
    "\xAA"
    "\xE1"
    "\xBB"
    "\xAB"
    "\xE1"
    "\xBB"
    "\xAD"
    "\xE1"
    "\xBB"
    "\xAF"
    "\xE1"
    "\xBB"
    "\xB1"
    "\xE1"
    "\xBB"
    "\xB3"
    "\xE1"
    "\xBB"
    "\xB5"
    "\xE1"
    "\xBB"
    "\xB7"
    "",  // Tiếng Việt
};

namespace i18n_strings {

const char* const STRINGS_EN[] = {
    "CrossPet",
    "BOOTING",
    "SLEEPING",
    "Going to sleep",
    "Browse Files",
    "File Transfer",
    "Settings",
    "Calibre Library",
    "Continue Reading",
    "No open book",
    "Start reading below",
    "Books",
    "No files found",
    "Select Chapter",
    "No chapters",
    "End of book",
    "Empty chapter",
    "Indexing",
    "Memory error",
    "Page load error",
    "Empty file",
    "Out of bounds",
    "Loading...",
    "Loading",
    "Failed to load XTC",
    "Failed to load TXT",
    "Failed to load EPUB",
    "SD card error",
    "WiFi Networks",
    "No networks found",
    "%zu networks found",
    "Scanning...",
    "Connecting...",
    "Connected!",
    "Connection Failed",
    "Connection timeout",
    "Forget Network?",
    "Save password for next time?",
    "Remove saved password?",
    "Press OK to scan again",
    "Press any button to continue",
    "LEFT/RIGHT: Select | OK: Confirm",
    "How would you like to connect?",
    "Join a Network",
    "Create Hotspot",
    "Connect to an existing WiFi network",
    "Create a WiFi network others can join",
    "Starting Hotspot...",
    "Hotspot Mode",
    "Connect your device to this WiFi network",
    "Open this URL in your browser",
    "or http://",
    "or scan QR code with your phone:",
    "Calibre Wireless",
    "Calibre Web URL",
    "Connect as Wireless Device",
    "* = Encrypted | + = Saved",
    "MAC address:",
    "Checking WiFi...",
    "Enter WiFi Password",
    "Enter Text",
    "to ",
    "Discovering Calibre...",
    "Connecting to ",
    "Connected to ",
    "Waiting for commands...",
    "(Connection failed, retrying)",
    "Calibre disconnected",
    "Waiting for transfer...",
    "If transfer fails, enable\n'Ignore free space' in Calibre's\nSmartDevice plugin settings.",
    "Receiving: ",
    "Received: ",
    "Waiting for more...",
    "Failed to create file",
    "Password required",
    "Transfer interrupted",
    "1) Install CrossPoint Reader plugin",
    "2) Be on the same WiFi network",
    "3) In Calibre: \"Send to device\"",
    "\"Keep this screen open while sending\"",
    "Display",
    "Reader",
    "Controls",
    "System",
    "Sleep Screen",
    "Sleep Screen Cover Mode",
    "Status Bar",
    "Hide Battery %",
    "Extra Paragraph Spacing",
    "Text Anti-Aliasing",
    "Text Darkness",
    "Extra Dark",
    "Images",
    "Display",
    "Placeholder",
    "Suppress",
    "Short Power Button Click",
    "Reading Orientation",
    "Front Button Layout",
    "Side Button Layout (reader)",
    "Front Button Layout (reader)",
    "Long-press Chapter Skip",
    "Reader Font Family",
    "External Reader Font",
    "Reader Font",
    "UI Font",
    "Reader Font Size",
    "Reader Line Spacing",
    "ASCII Letter Spacing",
    "ASCII Digit Spacing",
    "CJK Spacing",
    "Color Mode",
    "Reader Screen Margin",
    "Reader Paragraph Alignment",
    "Hyphenation",
    "Time to Sleep",
    "Show Hidden Files",
    "Refresh Frequency",
    "Calibre Settings",
    "KOReader Sync",
    "Check for updates",
    "Language",
    "Select Wallpaper",
    "Clear Reading Cache",
    "Calibre",
    "Username",
    "Password",
    "Sync Server URL",
    "Document Matching",
    "Authenticate",
    "KOReader Username",
    "KOReader Password",
    "Filename",
    "Binary",
    "Set credentials first",
    "WiFi connection failed",
    "Authenticating...",
    "Successfully authenticated!",
    "KOReader Auth",
    "KOReader sync is ready to use",
    "Authentication Failed",
    "Done",
    "This will clear all cached book data.",
    "All reading progress will be lost!",
    "Books will need to be re-indexed",
    "when opened again.",
    "Clearing cache...",
    "Cache Cleared",
    "items removed",
    "failed",
    "Failed to clear cache",
    "Check serial output for details",
    "Dark",
    "Light",
    "Custom",
    "Cover",
    "None",
    "Fit",
    "Crop",
    "No Progress",
    "Full",
    "Never",
    "In Reader",
    "Always",
    "Ignore",
    "Sleep",
    "Page Turn",
    "Screen Refresh",
    "Block Front",
    "Portrait",
    "Landscape CW",
    "Inverted",
    "Landscape CCW",
    "Bck, Cnfrm, Lft, Rght",
    "Lft, Rght, Bck, Cnfrm",
    "Lft, Bck, Cnfrm, Rght",
    "Prev/Next",
    "Next/Prev",
    "Bookerly",
    "Noto Sans",
    "Open Dyslexic",
    "Bokerlam",
    "Small",
    "Medium",
    "Large",
    "X Large",
    "Tight",
    "Normal",
    "Wide",
    "Justify",
    "Left",
    "Center",
    "Right",
    "1 min",
    "5 min",
    "10 min",
    "15 min",
    "30 min",
    "1 page",
    "5 pages",
    "10 pages",
    "15 pages",
    "30 pages",
    "Update",
    "Checking for update...",
    "New update available!",
    "Current Version: ",
    "New Version: ",
    "Updating...",
    "No update available",
    "Update failed",
    "Update complete",
    "Press and hold power button to turn back on",
    "External Font",
    "Built-in (Disabled)",
    "No entries found",
    "Downloading...",
    "Download failed",
    "Error:",
    "Unnamed",
    "No server URL configured",
    "Failed to fetch feed",
    "Failed to parse feed",
    "Network: ",
    "IP Address: ",
    "or scan QR code with your phone to connect to Wifi.",
    "Error: General failure",
    "Error: Network not found",
    "Error: Connection timeout",
    "SD card",
    "\xC2"
    "\xAB"
    " Back",
    "\xC2"
    "\xAB"
    " Exit",
    "\xC2"
    "\xAB"
    " Home",
    "\xC2"
    "\xAB"
    " Save",
    "Select",
    "Selected",
    "Toggle",
    "Confirm",
    "Cancel",
    "Connect",
    "Open",
    "Download",
    "Retry",
    "Yes",
    "No",
    "Show",
    "Hide",
    "ON",
    "OFF",
    "Not Set",
    "Left",
    "Right",
    "Up",
    "Down",
    "CAPS",
    "caps",
    "OK",
    "Sleep Screen Cover Filter",
    "Contrast",
    "Customise Status Bar",
    "Chapter Page Count",
    "Book Progress Percentage",
    "Progress Bar",
    "Progress Bar Thickness",
    "Thin",
    "Medium",
    "Thick",
    "Book",
    "Chapter",
    "Chapter 21",
    "Book Title",
    "Preview",
    "Title",
    "Battery",
    "UI Theme",
    "Classic",
    "Lyra",
    "Lyra Extended",
    "CrossPet Reader",
    "CrossPet Classic",
    "Sunlight Fading Fix",
    "Dark Mode",
    "Keep Clock Alive",
    "Off",
    "Sleep Refresh",
    "1 min",
    "5 min",
    "10 min",
    "30 min",
    "60 min",
    "Remap Front Buttons",
    "OPDS Browser",
    "Cover + Custom",
    "Page overlay",
    "Recents",
    "Recent Books",
    "No recent books",
    "Use Calibre wireless device transfers",
    "Forget network and remove saved password?",
    "Forget",
    "Starting Calibre...",
    "Setup",
    "Status",
    "Clear",
    "Default",
    "Press a front button for each role",
    "Unassigned",
    "Already assigned",
    "Side button Up: Reset to default layout",
    "Side button Down: Cancel remapping",
    "Back (1st button)",
    "Confirm (2nd button)",
    "Left (3rd button)",
    "Right (4th button)",
    "Go to %",
    "Go Home",
    "Sync Progress",
    "Delete Book Cache",
    "Delete",
    "Show page as QR",
    "Chapter: ",
    " pages  |  ",
    "Book: ",
    "shift",
    "SHIFT",
    "LOCK",
    "For Calibre, add /opds to your URL",
    "Left/Right: 1%  Up/Down: 10%",
    "Syncing time...",
    "Calculating document hash...",
    "Failed to calculate document hash",
    "Fetching remote progress...",
    "Uploading progress...",
    "No credentials configured",
    "Set up KOReader account in Settings",
    "Progress found!",
    "Remote:",
    "Local:",
    "Page %d, %.2f%% overall",
    "Page %d/%d, %.2f%% overall",
    "  From: %s",
    "Apply remote progress",
    "Upload local progress",
    "No remote progress found",
    "Upload current position?",
    "Progress uploaded!",
    "Sync failed",
    "Section ",
    "Upload",
    "Book's Style",
    "Embedded Style",
    "OPDS Server URL",
    "Footnotes",
    "No footnotes on this page",
    "[link]",
    "Take screenshot",
    "Auto Turn Enabled: ",
    "Auto Turn (Pages Per Minute)",
    "Auto Page Turn",
    "1 page/min",
    "3 pages/min",
    "6 pages/min",
    "12 pages/min",
    "Apps",
    "Clock",
    "Pomodoro",
    "Daily Quote",
    "Connect WiFi to sync time",
    "Place quotes.txt on SD card",
    "(Built-in quote)",
    "Ready",
    "Focus",
    "Short Break",
    "Long Break",
    "Paused",
    "Start",
    "Pause",
    "Resume",
    "Skip",
    "Bluetooth Remote",
    "Auto-connect BT",
    "Pair Remote",
    "Scanning...",
    "Connecting...",
    "Connected",
    "Not connected",
    "No devices found",
    "Paired: %s",
    "Forget Device",
    "Forget paired remote?",
    "Learn Keys",
    "Press NEXT on remote",
    "Press PREV on remote",
    "Keys learned!",
    "Presenter Pen",
    "Waiting for connection...",
    "Pair this device as a Bluetooth keyboard",
    "Right ->",
    "Next slide",
    "<- Left",
    "Prev slide",
    "OK",
    "Start (F5)",
    "Back",
    "End (Esc)",
    "Next >",
    "< Prev",
    "F5",
    "Esc",
    "My Pet",
    "Hunger",
    "Pet",
    "Health",
    "Egg",
    "Hatchling",
    "Youngster",
    "Companion",
    "Elder",
    "Your pet has passed...",
    "Hatch New Egg?",
    "No pet yet",
    "Hatch Egg?",
    "Weight",
    "Discipline",
    "Mistakes",
    "Sleeping",
    "Sick",
    "Dirty",
    "Needs attention!",
    "Scholarly Young",
    "Wild Youngster",
    "Scholar",
    "Wild Companion",
    "Nom nom! +Hunger",
    "Yummy! +Happy",
    "Feeling better~",
    "Great workout!",
    "All clean!",
    "Good discipline!",
    "That was mean...",
    "Good training!",
    "Feeling neglected...",
    "Goodnight~",
    "Lights on!",
    "Your pet lived a full life. Farewell~",
    "Your pet has passed from neglect...",
    "Too sick to eat...",
    "Shh... sleeping",
    "Not ready yet...",
    "Feed Meal",
    "Feed Snack",
    "Medicine",
    "Exercise",
    "Clean",
    "Scold",
    "Ignore",
    "Lights",
    "Pet",
    "Rename",
    "Change Type",
    "Pet Name",
    "Select Pet Type",
    "Chicken",
    "Cat",
    "Dog",
    "Dragon",
    "Bunny",
    "Robot",
    "Bear",
    "Slime",
    "Chapter Complete!",
    "%ud",
    "Daily goal reached!",
    "Streak up! %u days",
    "%lu pages read!",
    "%s: Feed me! Read more",
    "%s: I miss you...",
    "%s: I feel sick...",
    "%s: Play with me!",
    "%s: Zzz...",
    "%s: %ud streak!",
    "%s: Let's read!",
    "%s: Read with me~",
    "No pet!",
    "Not sick!",
    "Already clean!",
    "Too sick to exercise",
    "Nothing to ignore",
    "Hey! That's not fair...",
    "Read 20 pages",
    "Pet 3 times",
    "Keep fed (>40%)",
    "%s (%s)  |  Day %lu  |  Streak %u",
    "%s %s  |  Day %lu  |  Streak %u",
    "%s  |  Day %lu  |  Streak %u",
    "Photo Frame",
    "Maze",
    "Game of Life",
    "New Maze",
    "Snake",
    "2048",
    "New Game",
    "Reading Stats",
    "TODAY",
    "ALL TIME",
    "LAST BOOK",
    "Sessions",
    "Finished",
    "Streak",
    "Best",
    "%ud",
    "No books read yet",
    "Game Over!",
    "You Win!",
    "Score: %lu    Best: %lu",
    "Score:%d Hi:%d",
    "Up/Down: speed",
    "Done! %d moves",
    "Moves: %d",
    "Gen %lu",
    "Mistakes: %d",
    "No photos found",
    "Place .bmp files in /sleep/",
    "Happy",
    "Reading",
    "Feed me~",
    "Need medicine...",
    "It's dirty...",
    "So bored...",
    "Hey!",
    "Not feeling well...",
    "Zzz...",
    "Purr~",
    "Sweet dreams",
    "Dreaming...",
    "Hungry...",
    "Read more!",
    "%s | %d alive",
    "Fast",
    "Med",
    "Slow",
    "Slowest",
    "Sudoku",
    "Easy",
    "Medium",
    "Hard",
    "Completed!",
    "1-9",
    "Minesweeper",
    "Easy",
    "Medium",
    "Hard",
    "Mines: %d",
    "Reveal",
    "Flag",
    "Caro",
    "Turn: X",
    "Turn: O",
    "X Wins!",
    "O Wins!",
    "Draw!",
    "Place",
    "Easy",
    "Medium",
    "Hard",
    "Select Difficulty",
    "Chess",
    "White's Turn",
    "Black's Turn",
    "White Wins!",
    "Black Wins!",
    "Select",
    "Move",
    "Set Time",
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "S",
    "M",
    "T",
    "W",
    "T",
    "F",
    "S",
    "Lunar",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    "Hour",
    "Minute",
    "Day",
    "Month",
    "Year",
    "Sync time via WiFi",
    "Weather",
    "Fetching weather...",
    "Temperature",
    "\xC2"
    "\xB0"
    "C",
    "\xC2"
    "\xB0"
    "F",
    "Failed to load weather",
    "Feels like",
    "Humidity",
    "Wind",
    "Refresh",
    "City",
    "Clear sky",
    "Partly cloudy",
    "Fog",
    "Drizzle",
    "Rain",
    "Snow",
    "Showers",
    "Thunderstorm",
    "Updated",
    "Focus:",
    "Short break:",
    "Long break:",
    "%s %2lu min",
    "Start >",
    "Location",
    "Home clock",
    "Home weather",
    "Home pet status",
    "Reading Stats",
    "RECENTLY READ",
    "Today",
    "Total",
    "Sessions",
    "TIME READ",
    "%d times",
    "%d min",
    "%dh %dm",
    "Sync",
    "Sync OK",
    "WiFi timeout",
    "API error %d",
    "Sleep Image",
    "Image selected!",
    "No .bmp files found",
    "Place .bmp files in /sleep/",
    "Any (random)",
    "Set sleep screen to 'Custom' in Settings > Display",
    "Starred Pages",
    "Star Page",
    "No starred pages",
    "p",
    "Page starred",
    "Page unstarred",
    "Reload Sleep Image",
    "Sleep cache cleared!",
    "Sync Weather & Time",
    "Power Double-Click",
    "Power Triple-Click",
    "Show Free RAM",
};

const char* const STRINGS_VI[] = {
    "CrossPet",
    "\xC4"
    "\x90"
    "ANG KH\xE1"
    "\xBB"
    "\x9E"
    "I \xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x98"
    "NG",
    "NG\xE1"
    "\xBB"
    "\xA6"
    "",
    "\xC4"
    "\x90"
    "ang chuy\xE1"
    "\xBB"
    "\x83"
    "n sang ch\xE1"
    "\xBA"
    "\xBF"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x99"
    " ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "Th\xC6"
    "\xB0"
    " vi\xE1"
    "\xBB"
    "\x87"
    "n",
    "T\xE1"
    "\xBA"
    "\xA3"
    "i s\xC3"
    "\xA1"
    "ch",
    "C\xC3"
    "\xA0"
    "i \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xB7"
    "t",
    "Th\xC6"
    "\xB0"
    " vi\xE1"
    "\xBB"
    "\x87"
    "n Calibre",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8D"
    "c ti\xE1"
    "\xBA"
    "\xBF"
    "p",
    "Ch\xC6"
    "\xB0"
    "a m\xE1"
    "\xBB"
    "\x9F"
    " s\xC3"
    "\xA1"
    "ch n\xC3"
    "\xA0"
    "o",
    "B\xE1"
    "\xBA"
    "\xAF"
    "t \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xA7"
    "u \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c b\xC3"
    "\xAA"
    "n d\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "i",
    "S\xC3"
    "\xA1"
    "ch",
    "Kh\xC3"
    "\xB4"
    "ng t\xC3"
    "\xAC"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "y t\xE1"
    "\xBB"
    "\x87"
    "p",
    "Ch\xE1"
    "\xBB"
    "\x8D"
    "n ch\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng",
    "Kh\xC3"
    "\xB4"
    "ng c\xC3"
    "\xB3"
    " ch\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng",
    "H\xE1"
    "\xBA"
    "\xBF"
    "t s\xC3"
    "\xA1"
    "ch",
    "Ch\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng tr\xE1"
    "\xBB"
    "\x91"
    "ng",
    "\xC4"
    "\x90"
    "ang l\xE1"
    "\xBA"
    "\xAD"
    "p ch\xE1"
    "\xBB"
    "\x89"
    " m\xE1"
    "\xBB"
    "\xA5"
    "c",
    "L\xE1"
    "\xBB"
    "\x97"
    "i b\xE1"
    "\xBB"
    "\x99"
    " nh\xE1"
    "\xBB"
    "\x9B"
    "",
    "L\xE1"
    "\xBB"
    "\x97"
    "i t\xE1"
    "\xBA"
    "\xA3"
    "i trang",
    "T\xE1"
    "\xBB"
    "\x87"
    "p tr\xE1"
    "\xBB"
    "\x91"
    "ng",
    "V\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "t gi\xE1"
    "\xBB"
    "\x9B"
    "i h\xE1"
    "\xBA"
    "\xA1"
    "n",
    "\xC4"
    "\x90"
    "ang t\xE1"
    "\xBA"
    "\xA3"
    "i...",
    "\xC4"
    "\x90"
    "ang t\xE1"
    "\xBA"
    "\xA3"
    "i",
    "Kh\xC3"
    "\xB4"
    "ng t\xE1"
    "\xBA"
    "\xA3"
    "i \xC4"
    "\x91"
    "\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "c XTC",
    "Kh\xC3"
    "\xB4"
    "ng t\xE1"
    "\xBA"
    "\xA3"
    "i \xC4"
    "\x91"
    "\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "c TXT",
    "Kh\xC3"
    "\xB4"
    "ng t\xE1"
    "\xBA"
    "\xA3"
    "i \xC4"
    "\x91"
    "\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "c EPUB",
    "L\xE1"
    "\xBB"
    "\x97"
    "i th\xE1"
    "\xBA"
    "\xBB"
    " SD",
    "M\xE1"
    "\xBA"
    "\xA1"
    "ng WiFi",
    "Kh\xC3"
    "\xB4"
    "ng t\xC3"
    "\xAC"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "y m\xE1"
    "\xBA"
    "\xA1"
    "ng",
    "T\xC3"
    "\xAC"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "y %zu m\xE1"
    "\xBA"
    "\xA1"
    "ng",
    "\xC4"
    "\x90"
    "ang qu\xC3"
    "\xA9"
    "t...",
    "\xC4"
    "\x90"
    "ang k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i...",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i!",
    "K\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i",
    "H\xE1"
    "\xBA"
    "\xBF"
    "t th\xE1"
    "\xBB"
    "\x9D"
    "i gian k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i",
    "Qu\xC3"
    "\xAA"
    "n m\xE1"
    "\xBA"
    "\xA1"
    "ng n\xC3"
    "\xA0"
    "y?",
    "L\xC6"
    "\xB0"
    "u m\xE1"
    "\xBA"
    "\xAD"
    "t kh\xE1"
    "\xBA"
    "\xA9"
    "u?",
    "X\xC3"
    "\xB3"
    "a m\xE1"
    "\xBA"
    "\xAD"
    "t kh\xE1"
    "\xBA"
    "\xA9"
    "u \xC4"
    "\x91"
    "\xC3"
    "\xA3"
    " l\xC6"
    "\xB0"
    "u?",
    "Nh\xE1"
    "\xBA"
    "\xA5"
    "n OK \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x83"
    " qu\xC3"
    "\xA9"
    "t l\xE1"
    "\xBA"
    "\xA1"
    "i",
    "Nh\xE1"
    "\xBA"
    "\xA5"
    "n n\xC3"
    "\xBA"
    "t b\xE1"
    "\xBA"
    "\xA5"
    "t k\xE1"
    "\xBB"
    "\xB3"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x83"
    " ti\xE1"
    "\xBA"
    "\xBF"
    "p t\xE1"
    "\xBB"
    "\xA5"
    "c",
    "TR\xC3"
    "\x81"
    "I/PH\xE1"
    "\xBA"
    "\xA2"
    "I: Ch\xE1"
    "\xBB"
    "\x8D"
    "n | OK: X\xC3"
    "\xA1"
    "c nh\xE1"
    "\xBA"
    "\xAD"
    "n",
    "B\xE1"
    "\xBA"
    "\xA1"
    "n mu\xE1"
    "\xBB"
    "\x91"
    "n k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i th\xE1"
    "\xBA"
    "\xBF"
    " n\xC3"
    "\xA0"
    "o?",
    "K\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i m\xE1"
    "\xBA"
    "\xA1"
    "ng",
    "T\xE1"
    "\xBA"
    "\xA1"
    "o \xC4"
    "\x91"
    "i\xE1"
    "\xBB"
    "\x83"
    "m ph\xC3"
    "\xA1"
    "t",
    "K\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i v\xC3"
    "\xA0"
    "o m\xE1"
    "\xBA"
    "\xA1"
    "ng WiFi c\xC3"
    "\xB3"
    " s\xE1"
    "\xBA"
    "\xB5"
    "n",
    "T\xE1"
    "\xBA"
    "\xA1"
    "o m\xE1"
    "\xBA"
    "\xA1"
    "ng WiFi cho thi\xE1"
    "\xBA"
    "\xBF"
    "t b\xE1"
    "\xBB"
    "\x8B"
    " kh\xC3"
    "\xA1"
    "c",
    "\xC4"
    "\x90"
    "ang t\xE1"
    "\xBA"
    "\xA1"
    "o \xC4"
    "\x91"
    "i\xE1"
    "\xBB"
    "\x83"
    "m ph\xC3"
    "\xA1"
    "t...",
    "Ch\xE1"
    "\xBA"
    "\xBF"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x99"
    " \xC4"
    "\x91"
    "i\xE1"
    "\xBB"
    "\x83"
    "m ph\xC3"
    "\xA1"
    "t",
    "K\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i thi\xE1"
    "\xBA"
    "\xBF"
    "t b\xE1"
    "\xBB"
    "\x8B"
    " v\xC3"
    "\xA0"
    "o m\xE1"
    "\xBA"
    "\xA1"
    "ng WiFi n\xC3"
    "\xA0"
    "y",
    "M\xE1"
    "\xBB"
    "\x9F"
    " URL n\xC3"
    "\xA0"
    "y tr\xC3"
    "\xAA"
    "n tr\xC3"
    "\xAC"
    "nh duy\xE1"
    "\xBB"
    "\x87"
    "t",
    "ho\xE1"
    "\xBA"
    "\xB7"
    "c http://",
    "ho\xE1"
    "\xBA"
    "\xB7"
    "c qu\xC3"
    "\xA9"
    "t m\xC3"
    "\xA3"
    " QR b\xE1"
    "\xBA"
    "\xB1"
    "ng \xC4"
    "\x91"
    "i\xE1"
    "\xBB"
    "\x87"
    "n tho\xE1"
    "\xBA"
    "\xA1"
    "i:",
    "Calibre kh\xC3"
    "\xB4"
    "ng d\xC3"
    "\xA2"
    "y",
    "URL Web Calibre",
    "K\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i thi\xE1"
    "\xBA"
    "\xBF"
    "t b\xE1"
    "\xBB"
    "\x8B"
    " kh\xC3"
    "\xB4"
    "ng d\xC3"
    "\xA2"
    "y",
    "* = M\xC3"
    "\xA3"
    " h\xC3"
    "\xB3"
    "a | + = \xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " l\xC6"
    "\xB0"
    "u",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8B"
    "a ch\xE1"
    "\xBB"
    "\x89"
    " MAC:",
    "\xC4"
    "\x90"
    "ang ki\xE1"
    "\xBB"
    "\x83"
    "m tra WiFi...",
    "Nh\xE1"
    "\xBA"
    "\xAD"
    "p m\xE1"
    "\xBA"
    "\xAD"
    "t kh\xE1"
    "\xBA"
    "\xA9"
    "u WiFi",
    "Nh\xE1"
    "\xBA"
    "\xAD"
    "p v\xC4"
    "\x83"
    "n b\xE1"
    "\xBA"
    "\xA3"
    "n",
    "\xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xBF"
    "n ",
    "\xC4"
    "\x90"
    "ang t\xC3"
    "\xAC"
    "m Calibre...",
    "\xC4"
    "\x90"
    "ang k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i t\xE1"
    "\xBB"
    "\x9B"
    "i ",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i t\xE1"
    "\xBB"
    "\x9B"
    "i ",
    "\xC4"
    "\x90"
    "ang ch\xE1"
    "\xBB"
    "\x9D"
    " l\xE1"
    "\xBB"
    "\x87"
    "nh...",
    "(K\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i, \xC4"
    "\x91"
    "ang th\xE1"
    "\xBB"
    "\xAD"
    " l\xE1"
    "\xBA"
    "\xA1"
    "i)",
    "Calibre \xC4"
    "\x91"
    "\xC3"
    "\xA3"
    " ng\xE1"
    "\xBA"
    "\xAF"
    "t k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i",
    "\xC4"
    "\x90"
    "ang ch\xE1"
    "\xBB"
    "\x9D"
    " truy\xE1"
    "\xBB"
    "\x81"
    "n t\xE1"
    "\xBB"
    "\x87"
    "p...",
    "N\xE1"
    "\xBA"
    "\xBF"
    "u th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i, b\xE1"
    "\xBA"
    "\xAD"
    "t\n'B\xE1"
    "\xBB"
    "\x8F"
    " qua dung l\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "ng tr\xE1"
    "\xBB"
    "\x91"
    "ng' trong\nc\xC3"
    "\xA0"
    "i \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xB7"
    "t plugin SmartDevice c\xE1"
    "\xBB"
    "\xA7"
    "a Calibre.",
    "\xC4"
    "\x90"
    "ang nh\xE1"
    "\xBA"
    "\xAD"
    "n: ",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " nh\xE1"
    "\xBA"
    "\xAD"
    "n: ",
    "\xC4"
    "\x90"
    "ang ch\xE1"
    "\xBB"
    "\x9D"
    " th\xC3"
    "\xAA"
    "m...",
    "Kh\xC3"
    "\xB4"
    "ng t\xE1"
    "\xBA"
    "\xA1"
    "o \xC4"
    "\x91"
    "\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "c t\xE1"
    "\xBB"
    "\x87"
    "p",
    "Y\xC3"
    "\xAA"
    "u c\xE1"
    "\xBA"
    "\xA7"
    "u m\xE1"
    "\xBA"
    "\xAD"
    "t kh\xE1"
    "\xBA"
    "\xA9"
    "u",
    "Truy\xE1"
    "\xBB"
    "\x81"
    "n t\xE1"
    "\xBB"
    "\x87"
    "p b\xE1"
    "\xBB"
    "\x8B"
    " gi\xC3"
    "\xA1"
    "n \xC4"
    "\x91"
    "o\xE1"
    "\xBA"
    "\xA1"
    "n",
    "1) C\xC3"
    "\xA0"
    "i plugin CrossPoint Reader",
    "2) C\xC3"
    "\xB9"
    "ng m\xE1"
    "\xBA"
    "\xA1"
    "ng WiFi",
    "3) Calibre: \"G\xE1"
    "\xBB"
    "\xAD"
    "i t\xE1"
    "\xBB"
    "\x9B"
    "i thi\xE1"
    "\xBA"
    "\xBF"
    "t b\xE1"
    "\xBB"
    "\x8B"
    "\"",
    "\"Gi\xE1"
    "\xBB"
    "\xAF"
    " m\xC3"
    "\xA0"
    "n h\xC3"
    "\xAC"
    "nh n\xC3"
    "\xA0"
    "y khi \xC4"
    "\x91"
    "ang g\xE1"
    "\xBB"
    "\xAD"
    "i\"",
    "Hi\xE1"
    "\xBB"
    "\x83"
    "n th\xE1"
    "\xBB"
    "\x8B"
    "",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8D"
    "c s\xC3"
    "\xA1"
    "ch",
    "\xC4"
    "\x90"
    "i\xE1"
    "\xBB"
    "\x81"
    "u khi\xE1"
    "\xBB"
    "\x83"
    "n",
    "H\xE1"
    "\xBB"
    "\x87"
    " th\xE1"
    "\xBB"
    "\x91"
    "ng",
    "M\xC3"
    "\xA0"
    "n h\xC3"
    "\xAC"
    "nh ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "Ch\xE1"
    "\xBA"
    "\xBF"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x99"
    " b\xC3"
    "\xAC"
    "a khi ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "Thanh tr\xE1"
    "\xBA"
    "\xA1"
    "ng th\xC3"
    "\xA1"
    "i",
    "\xE1"
    "\xBA"
    "\xA8"
    "n % pin",
    "Kho\xE1"
    "\xBA"
    "\xA3"
    "ng c\xC3"
    "\xA1"
    "ch \xC4"
    "\x91"
    "o\xE1"
    "\xBA"
    "\xA1"
    "n v\xC4"
    "\x83"
    "n",
    "Kh\xE1"
    "\xBB"
    "\xAD"
    " r\xC4"
    "\x83"
    "ng c\xC6"
    "\xB0"
    "a",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x99"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xAD"
    "m ch\xE1"
    "\xBB"
    "\xAF"
    "",
    "R\xE1"
    "\xBA"
    "\xA5"
    "t \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xAD"
    "m",
    "H\xC3"
    "\xAC"
    "nh \xE1"
    "\xBA"
    "\xA3"
    "nh",
    "Hi\xE1"
    "\xBB"
    "\x83"
    "n th\xE1"
    "\xBB"
    "\x8B"
    "",
    "Gi\xE1"
    "\xBB"
    "\xAF"
    " ch\xE1"
    "\xBB"
    "\x97"
    "",
    "\xE1"
    "\xBA"
    "\xA8"
    "n",
    "Nh\xE1"
    "\xBA"
    "\xA5"
    "n nhanh n\xC3"
    "\xBA"
    "t ngu\xE1"
    "\xBB"
    "\x93"
    "n",
    "H\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "ng \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c",
    "B\xE1"
    "\xBB"
    "\x91"
    " tr\xC3"
    "\xAD"
    " n\xC3"
    "\xBA"
    "t tr\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c",
    "N\xC3"
    "\xBA"
    "t b\xC3"
    "\xAA"
    "n (\xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c s\xC3"
    "\xA1"
    "ch)",
    "Front Button Layout (reader)",
    "Gi\xE1"
    "\xBB"
    "\xAF"
    " l\xC3"
    "\xA2"
    "u chuy\xE1"
    "\xBB"
    "\x83"
    "n ch\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng",
    "Ph\xC3"
    "\xB4"
    "ng ch\xE1"
    "\xBB"
    "\xAF"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c s\xC3"
    "\xA1"
    "ch",
    "Ph\xC3"
    "\xB4"
    "ng ch\xE1"
    "\xBB"
    "\xAF"
    " ngo\xC3"
    "\xA0"
    "i",
    "Ph\xC3"
    "\xB4"
    "ng ch\xE1"
    "\xBB"
    "\xAF"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c",
    "Ph\xC3"
    "\xB4"
    "ng ch\xE1"
    "\xBB"
    "\xAF"
    " giao di\xE1"
    "\xBB"
    "\x87"
    "n",
    "C\xE1"
    "\xBB"
    "\xA1"
    " ch\xE1"
    "\xBB"
    "\xAF"
    " giao di\xE1"
    "\xBB"
    "\x87"
    "n",
    "Gi\xC3"
    "\xA3"
    "n d\xC3"
    "\xB2"
    "ng",
    "Gi\xC3"
    "\xA3"
    "n ch\xE1"
    "\xBB"
    "\xAF"
    " ASCII",
    "Gi\xC3"
    "\xA3"
    "n s\xE1"
    "\xBB"
    "\x91"
    " ASCII",
    "Gi\xC3"
    "\xA3"
    "n ch\xE1"
    "\xBB"
    "\xAF"
    " CJK",
    "Ch\xE1"
    "\xBA"
    "\xBF"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x99"
    " m\xC3"
    "\xA0"
    "u",
    "L\xE1"
    "\xBB"
    "\x81"
    " m\xC3"
    "\xA0"
    "n h\xC3"
    "\xAC"
    "nh \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c",
    "C\xC4"
    "\x83"
    "n l\xE1"
    "\xBB"
    "\x81"
    " \xC4"
    "\x91"
    "o\xE1"
    "\xBA"
    "\xA1"
    "n v\xC4"
    "\x83"
    "n",
    "Ng\xE1"
    "\xBA"
    "\xAF"
    "t t\xE1"
    "\xBB"
    "\xAB"
    "",
    "Th\xE1"
    "\xBB"
    "\x9D"
    "i gian ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "Show Hidden Files",
    "T\xE1"
    "\xBA"
    "\xA7"
    "n su\xE1"
    "\xBA"
    "\xA5"
    "t l\xC3"
    "\xA0"
    "m m\xE1"
    "\xBB"
    "\x9B"
    "i",
    "C\xC3"
    "\xA0"
    "i \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xB7"
    "t Calibre",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    " KOReader",
    "Ki\xE1"
    "\xBB"
    "\x83"
    "m tra c\xE1"
    "\xBA"
    "\xAD"
    "p nh\xE1"
    "\xBA"
    "\xAD"
    "t",
    "Ng\xC3"
    "\xB4"
    "n ng\xE1"
    "\xBB"
    "\xAF"
    "",
    "Ch\xE1"
    "\xBB"
    "\x8D"
    "n h\xC3"
    "\xAC"
    "nh n\xE1"
    "\xBB"
    "\x81"
    "n",
    "X\xC3"
    "\xB3"
    "a b\xE1"
    "\xBB"
    "\x99"
    " nh\xE1"
    "\xBB"
    "\x9B"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x87"
    "m",
    "Calibre",
    "T\xC3"
    "\xAA"
    "n ng\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9D"
    "i d\xC3"
    "\xB9"
    "ng",
    "M\xE1"
    "\xBA"
    "\xAD"
    "t kh\xE1"
    "\xBA"
    "\xA9"
    "u",
    "URL m\xC3"
    "\xA1"
    "y ch\xE1"
    "\xBB"
    "\xA7"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    "",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x91"
    "i chi\xE1"
    "\xBA"
    "\xBF"
    "u t\xC3"
    "\xA0"
    "i li\xE1"
    "\xBB"
    "\x87"
    "u",
    "X\xC3"
    "\xA1"
    "c th\xE1"
    "\xBB"
    "\xB1"
    "c",
    "T\xC3"
    "\xAA"
    "n ng\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9D"
    "i d\xC3"
    "\xB9"
    "ng KOReader",
    "M\xE1"
    "\xBA"
    "\xAD"
    "t kh\xE1"
    "\xBA"
    "\xA9"
    "u KOReader",
    "T\xC3"
    "\xAA"
    "n t\xE1"
    "\xBB"
    "\x87"
    "p",
    "Nh\xE1"
    "\xBB"
    "\x8B"
    " ph\xC3"
    "\xA2"
    "n",
    "C\xE1"
    "\xBA"
    "\xA7"
    "n nh\xE1"
    "\xBA"
    "\xAD"
    "p th\xC3"
    "\xB4"
    "ng tin \xC4"
    "\x91"
    "\xC4"
    "\x83"
    "ng nh\xE1"
    "\xBA"
    "\xAD"
    "p",
    "K\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i WiFi th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i",
    "\xC4"
    "\x90"
    "ang x\xC3"
    "\xA1"
    "c th\xE1"
    "\xBB"
    "\xB1"
    "c...",
    "X\xC3"
    "\xA1"
    "c th\xE1"
    "\xBB"
    "\xB1"
    "c th\xC3"
    "\xA0"
    "nh c\xC3"
    "\xB4"
    "ng!",
    "X\xC3"
    "\xA1"
    "c th\xE1"
    "\xBB"
    "\xB1"
    "c KOReader",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    " KOReader s\xE1"
    "\xBA"
    "\xB5"
    "n s\xC3"
    "\xA0"
    "ng",
    "X\xC3"
    "\xA1"
    "c th\xE1"
    "\xBB"
    "\xB1"
    "c th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i",
    "Xong",
    "To\xC3"
    "\xA0"
    "n b\xE1"
    "\xBB"
    "\x99"
    " d\xE1"
    "\xBB"
    "\xAF"
    " li\xE1"
    "\xBB"
    "\x87"
    "u \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x87"
    "m s\xE1"
    "\xBA"
    "\xBD"
    " b\xE1"
    "\xBB"
    "\x8B"
    " x\xC3"
    "\xB3"
    "a.",
    "Ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c s\xE1"
    "\xBA"
    "\xBD"
    " b\xE1"
    "\xBB"
    "\x8B"
    " m\xE1"
    "\xBA"
    "\xA5"
    "t!",
    "S\xC3"
    "\xA1"
    "ch s\xE1"
    "\xBA"
    "\xBD"
    " c\xE1"
    "\xBA"
    "\xA7"
    "n l\xE1"
    "\xBA"
    "\xAD"
    "p ch\xE1"
    "\xBB"
    "\x89"
    " m\xE1"
    "\xBB"
    "\xA5"
    "c l\xE1"
    "\xBA"
    "\xA1"
    "i",
    "khi m\xE1"
    "\xBB"
    "\x9F"
    " l\xE1"
    "\xBA"
    "\xA1"
    "i.",
    "\xC4"
    "\x90"
    "ang x\xC3"
    "\xB3"
    "a b\xE1"
    "\xBB"
    "\x99"
    " nh\xE1"
    "\xBB"
    "\x9B"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x87"
    "m...",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " x\xC3"
    "\xB3"
    "a b\xE1"
    "\xBB"
    "\x99"
    " nh\xE1"
    "\xBB"
    "\x9B"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x87"
    "m",
    "m\xE1"
    "\xBB"
    "\xA5"
    "c \xC4"
    "\x91"
    "\xC3"
    "\xA3"
    " x\xC3"
    "\xB3"
    "a",
    "th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i",
    "X\xC3"
    "\xB3"
    "a b\xE1"
    "\xBB"
    "\x99"
    " nh\xE1"
    "\xBB"
    "\x9B"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x87"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i",
    "Xem \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xA7"
    "u ra serial \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x83"
    " bi\xE1"
    "\xBA"
    "\xBF"
    "t chi ti\xE1"
    "\xBA"
    "\xBF"
    "t",
    "T\xE1"
    "\xBB"
    "\x91"
    "i",
    "S\xC3"
    "\xA1"
    "ng",
    "T\xC3"
    "\xB9"
    "y ch\xE1"
    "\xBB"
    "\x89"
    "nh",
    "B\xC3"
    "\xAC"
    "a s\xC3"
    "\xA1"
    "ch",
    "Kh\xC3"
    "\xB4"
    "ng",
    "V\xE1"
    "\xBB"
    "\xAB"
    "a khung",
    "C\xE1"
    "\xBA"
    "\xAF"
    "t",
    "Kh\xC3"
    "\xB4"
    "ng ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh",
    "To\xC3"
    "\xA0"
    "n ph\xE1"
    "\xBA"
    "\xA7"
    "n",
    "Kh\xC3"
    "\xB4"
    "ng bao gi\xE1"
    "\xBB"
    "\x9D"
    "",
    "Trong tr\xC3"
    "\xAC"
    "nh \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c",
    "Lu\xC3"
    "\xB4"
    "n lu\xC3"
    "\xB4"
    "n",
    "B\xE1"
    "\xBB"
    "\x8F"
    " qua",
    "Ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "L\xE1"
    "\xBA"
    "\xAD"
    "t trang",
    "L\xC3"
    "\xA0"
    "m m\xE1"
    "\xBB"
    "\x9B"
    "i m\xC3"
    "\xA0"
    "n h\xC3"
    "\xAC"
    "nh",
    "Block Front",
    "D\xE1"
    "\xBB"
    "\x8D"
    "c",
    "Ngang thu\xE1"
    "\xBA"
    "\xAD"
    "n",
    "Ng\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "c",
    "Ngang ngh\xE1"
    "\xBB"
    "\x8B"
    "ch",
    "L\xC3"
    "\xB9"
    "i, OK, Tr\xC3"
    "\xA1"
    "i, Ph\xE1"
    "\xBA"
    "\xA3"
    "i",
    "Tr\xC3"
    "\xA1"
    "i, Ph\xE1"
    "\xBA"
    "\xA3"
    "i, L\xC3"
    "\xB9"
    "i, OK",
    "Tr\xC3"
    "\xA1"
    "i, L\xC3"
    "\xB9"
    "i, OK, Ph\xE1"
    "\xBA"
    "\xA3"
    "i",
    "Tr\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c/Sau",
    "Sau/Tr\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c",
    "Bookerly",
    "Noto Sans",
    "Open Dyslexic",
    "Bokerlam",
    "Nh\xE1"
    "\xBB"
    "\x8F"
    "",
    "V\xE1"
    "\xBB"
    "\xAB"
    "a",
    "L\xE1"
    "\xBB"
    "\x9B"
    "n",
    "R\xE1"
    "\xBA"
    "\xA5"
    "t l\xE1"
    "\xBB"
    "\x9B"
    "n",
    "H\xE1"
    "\xBA"
    "\xB9"
    "p",
    "Th\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9D"
    "ng",
    "R\xE1"
    "\xBB"
    "\x99"
    "ng",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x81"
    "u hai b\xC3"
    "\xAA"
    "n",
    "Tr\xC3"
    "\xA1"
    "i",
    "Gi\xE1"
    "\xBB"
    "\xAF"
    "a",
    "Ph\xE1"
    "\xBA"
    "\xA3"
    "i",
    "1 ph\xC3"
    "\xBA"
    "t",
    "5 ph\xC3"
    "\xBA"
    "t",
    "10 ph\xC3"
    "\xBA"
    "t",
    "15 ph\xC3"
    "\xBA"
    "t",
    "30 ph\xC3"
    "\xBA"
    "t",
    "1 trang",
    "5 trang",
    "10 trang",
    "15 trang",
    "30 trang",
    "C\xE1"
    "\xBA"
    "\xAD"
    "p nh\xE1"
    "\xBA"
    "\xAD"
    "t",
    "\xC4"
    "\x90"
    "ang ki\xE1"
    "\xBB"
    "\x83"
    "m tra c\xE1"
    "\xBA"
    "\xAD"
    "p nh\xE1"
    "\xBA"
    "\xAD"
    "t...",
    "C\xC3"
    "\xB3"
    " b\xE1"
    "\xBA"
    "\xA3"
    "n c\xE1"
    "\xBA"
    "\xAD"
    "p nh\xE1"
    "\xBA"
    "\xAD"
    "t m\xE1"
    "\xBB"
    "\x9B"
    "i!",
    "Phi\xC3"
    "\xAA"
    "n b\xE1"
    "\xBA"
    "\xA3"
    "n hi\xE1"
    "\xBB"
    "\x87"
    "n t\xE1"
    "\xBA"
    "\xA1"
    "i: ",
    "Phi\xC3"
    "\xAA"
    "n b\xE1"
    "\xBA"
    "\xA3"
    "n m\xE1"
    "\xBB"
    "\x9B"
    "i: ",
    "\xC4"
    "\x90"
    "ang c\xE1"
    "\xBA"
    "\xAD"
    "p nh\xE1"
    "\xBA"
    "\xAD"
    "t...",
    "Kh\xC3"
    "\xB4"
    "ng c\xC3"
    "\xB3"
    " c\xE1"
    "\xBA"
    "\xAD"
    "p nh\xE1"
    "\xBA"
    "\xAD"
    "t",
    "C\xE1"
    "\xBA"
    "\xAD"
    "p nh\xE1"
    "\xBA"
    "\xAD"
    "t th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i",
    "C\xE1"
    "\xBA"
    "\xAD"
    "p nh\xE1"
    "\xBA"
    "\xAD"
    "t ho\xC3"
    "\xA0"
    "n t\xE1"
    "\xBA"
    "\xA5"
    "t",
    "Gi\xE1"
    "\xBB"
    "\xAF"
    " n\xC3"
    "\xBA"
    "t ngu\xE1"
    "\xBB"
    "\x93"
    "n \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x83"
    " b\xE1"
    "\xBA"
    "\xAD"
    "t l\xE1"
    "\xBA"
    "\xA1"
    "i",
    "Ph\xC3"
    "\xB4"
    "ng ch\xE1"
    "\xBB"
    "\xAF"
    " ngo\xC3"
    "\xA0"
    "i",
    "T\xC3"
    "\xAD"
    "ch h\xE1"
    "\xBB"
    "\xA3"
    "p (T\xE1"
    "\xBA"
    "\xAF"
    "t)",
    "Kh\xC3"
    "\xB4"
    "ng t\xC3"
    "\xAC"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "y m\xE1"
    "\xBB"
    "\xA5"
    "c n\xC3"
    "\xA0"
    "o",
    "\xC4"
    "\x90"
    "ang t\xE1"
    "\xBA"
    "\xA3"
    "i xu\xE1"
    "\xBB"
    "\x91"
    "ng...",
    "T\xE1"
    "\xBA"
    "\xA3"
    "i xu\xE1"
    "\xBB"
    "\x91"
    "ng th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i",
    "L\xE1"
    "\xBB"
    "\x97"
    "i:",
    "Kh\xC3"
    "\xB4"
    "ng t\xC3"
    "\xAA"
    "n",
    "Ch\xC6"
    "\xB0"
    "a c\xE1"
    "\xBA"
    "\xA5"
    "u h\xC3"
    "\xAC"
    "nh URL m\xC3"
    "\xA1"
    "y ch\xE1"
    "\xBB"
    "\xA7"
    "",
    "Kh\xC3"
    "\xB4"
    "ng l\xE1"
    "\xBA"
    "\xA5"
    "y \xC4"
    "\x91"
    "\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "c ngu\xE1"
    "\xBB"
    "\x93"
    "n c\xE1"
    "\xBA"
    "\xA5"
    "p",
    "Kh\xC3"
    "\xB4"
    "ng ph\xC3"
    "\xA2"
    "n t\xC3"
    "\xAD"
    "ch \xC4"
    "\x91"
    "\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "c ngu\xE1"
    "\xBB"
    "\x93"
    "n c\xE1"
    "\xBA"
    "\xA5"
    "p",
    "M\xE1"
    "\xBA"
    "\xA1"
    "ng: ",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8B"
    "a ch\xE1"
    "\xBB"
    "\x89"
    " IP: ",
    "ho\xE1"
    "\xBA"
    "\xB7"
    "c qu\xC3"
    "\xA9"
    "t m\xC3"
    "\xA3"
    " QR \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x83"
    " k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i WiFi.",
    "L\xE1"
    "\xBB"
    "\x97"
    "i: Th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i chung",
    "L\xE1"
    "\xBB"
    "\x97"
    "i: Kh\xC3"
    "\xB4"
    "ng t\xC3"
    "\xAC"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "y m\xE1"
    "\xBA"
    "\xA1"
    "ng",
    "L\xE1"
    "\xBB"
    "\x97"
    "i: H\xE1"
    "\xBA"
    "\xBF"
    "t th\xE1"
    "\xBB"
    "\x9D"
    "i gian k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i",
    "Th\xE1"
    "\xBA"
    "\xBB"
    " SD",
    "\xC2"
    "\xAB"
    " Quay l\xE1"
    "\xBA"
    "\xA1"
    "i",
    "\xC2"
    "\xAB"
    " Tho\xC3"
    "\xA1"
    "t",
    "\xC2"
    "\xAB"
    " Trang ch\xE1"
    "\xBB"
    "\xA7"
    "",
    "\xC2"
    "\xAB"
    " L\xC6"
    "\xB0"
    "u",
    "Ch\xE1"
    "\xBB"
    "\x8D"
    "n",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " ch\xE1"
    "\xBB"
    "\x8D"
    "n",
    "B\xE1"
    "\xBA"
    "\xAD"
    "t/T\xE1"
    "\xBA"
    "\xAF"
    "t",
    "X\xC3"
    "\xA1"
    "c nh\xE1"
    "\xBA"
    "\xAD"
    "n",
    "H\xE1"
    "\xBB"
    "\xA7"
    "y",
    "K\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i",
    "M\xE1"
    "\xBB"
    "\x9F"
    "",
    "T\xE1"
    "\xBA"
    "\xA3"
    "i xu\xE1"
    "\xBB"
    "\x91"
    "ng",
    "Th\xE1"
    "\xBB"
    "\xAD"
    " l\xE1"
    "\xBA"
    "\xA1"
    "i",
    "C\xC3"
    "\xB3"
    "",
    "Kh\xC3"
    "\xB4"
    "ng",
    "Hi\xE1"
    "\xBB"
    "\x87"
    "n",
    "\xE1"
    "\xBA"
    "\xA8"
    "n",
    "B\xE1"
    "\xBA"
    "\xAC"
    "T",
    "T\xE1"
    "\xBA"
    "\xAE"
    "T",
    "Ch\xC6"
    "\xB0"
    "a \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xB7"
    "t",
    "Tr\xC3"
    "\xA1"
    "i",
    "Ph\xE1"
    "\xBA"
    "\xA3"
    "i",
    "L\xC3"
    "\xAA"
    "n",
    "Xu\xE1"
    "\xBB"
    "\x91"
    "ng",
    "HOA",
    "th\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9D"
    "ng",
    "OK",
    "B\xE1"
    "\xBB"
    "\x99"
    " l\xE1"
    "\xBB"
    "\x8D"
    "c b\xC3"
    "\xAC"
    "a khi ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "T\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng ph\xE1"
    "\xBA"
    "\xA3"
    "n",
    "T\xC3"
    "\xB9"
    "y ch\xE1"
    "\xBB"
    "\x89"
    "nh thanh tr\xE1"
    "\xBA"
    "\xA1"
    "ng th\xC3"
    "\xA1"
    "i",
    "S\xE1"
    "\xBB"
    "\x91"
    " trang ch\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng",
    "Ph\xE1"
    "\xBA"
    "\xA7"
    "n tr\xC4"
    "\x83"
    "m ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh s\xC3"
    "\xA1"
    "ch",
    "Thanh ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x99"
    " d\xC3"
    "\xA0"
    "y thanh ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh",
    "M\xE1"
    "\xBB"
    "\x8F"
    "ng",
    "V\xE1"
    "\xBB"
    "\xAB"
    "a",
    "D\xC3"
    "\xA0"
    "y",
    "S\xC3"
    "\xA1"
    "ch",
    "Ch\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng",
    "Ch\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng 21",
    "T\xC3"
    "\xAA"
    "n s\xC3"
    "\xA1"
    "ch",
    "Xem tr\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c",
    "Ti\xC3"
    "\xAA"
    "u \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x81"
    "",
    "Pin",
    "Giao di\xE1"
    "\xBB"
    "\x87"
    "n",
    "C\xE1"
    "\xBB"
    "\x95"
    " \xC4"
    "\x91"
    "i\xE1"
    "\xBB"
    "\x83"
    "n",
    "Lyra",
    "Lyra M\xE1"
    "\xBB"
    "\x9F"
    " r\xE1"
    "\xBB"
    "\x99"
    "ng",
    "CrossPet Reader",
    "CrossPet Classic",
    "S\xE1"
    "\xBB"
    "\xAD"
    "a m\xE1"
    "\xBB"
    "\x9D"
    " n\xE1"
    "\xBA"
    "\xAF"
    "ng",
    "Dark Mode",
    "Keep Clock Alive",
    "Off",
    "Sleep Refresh",
    "1 min",
    "5 min",
    "10 min",
    "30 min",
    "60 min",
    "G\xC3"
    "\xA1"
    "n l\xE1"
    "\xBA"
    "\xA1"
    "i n\xC3"
    "\xBA"
    "t tr\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c",
    "Tr\xC3"
    "\xAC"
    "nh duy\xE1"
    "\xBB"
    "\x87"
    "t OPDS",
    "B\xC3"
    "\xAC"
    "a + T\xC3"
    "\xB9"
    "y ch\xE1"
    "\xBB"
    "\x89"
    "nh",
    "Page overlay",
    "G\xE1"
    "\xBA"
    "\xA7"
    "n \xC4"
    "\x91"
    "\xC3"
    "\xA2"
    "y",
    "S\xC3"
    "\xA1"
    "ch \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c g\xE1"
    "\xBA"
    "\xA7"
    "n \xC4"
    "\x91"
    "\xC3"
    "\xA2"
    "y",
    "Kh\xC3"
    "\xB4"
    "ng c\xC3"
    "\xB3"
    " s\xC3"
    "\xA1"
    "ch g\xE1"
    "\xBA"
    "\xA7"
    "n \xC4"
    "\x91"
    "\xC3"
    "\xA2"
    "y",
    "Truy\xE1"
    "\xBB"
    "\x81"
    "n kh\xC3"
    "\xB4"
    "ng d\xC3"
    "\xA2"
    "y qua Calibre",
    "Qu\xC3"
    "\xAA"
    "n m\xE1"
    "\xBA"
    "\xA1"
    "ng v\xC3"
    "\xA0"
    " x\xC3"
    "\xB3"
    "a m\xE1"
    "\xBA"
    "\xAD"
    "t kh\xE1"
    "\xBA"
    "\xA9"
    "u?",
    "Qu\xC3"
    "\xAA"
    "n",
    "\xC4"
    "\x90"
    "ang kh\xE1"
    "\xBB"
    "\x9F"
    "i \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x99"
    "ng Calibre...",
    "Thi\xE1"
    "\xBA"
    "\xBF"
    "t l\xE1"
    "\xBA"
    "\xAD"
    "p",
    "Tr\xE1"
    "\xBA"
    "\xA1"
    "ng th\xC3"
    "\xA1"
    "i",
    "X\xC3"
    "\xB3"
    "a",
    "M\xE1"
    "\xBA"
    "\xB7"
    "c \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8B"
    "nh",
    "Nh\xE1"
    "\xBA"
    "\xA5"
    "n n\xC3"
    "\xBA"
    "t tr\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c cho t\xE1"
    "\xBB"
    "\xAB"
    "ng ch\xE1"
    "\xBB"
    "\xA9"
    "c n\xC4"
    "\x83"
    "ng",
    "Ch\xC6"
    "\xB0"
    "a g\xC3"
    "\xA1"
    "n",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " g\xC3"
    "\xA1"
    "n r\xE1"
    "\xBB"
    "\x93"
    "i",
    "N\xC3"
    "\xBA"
    "t b\xC3"
    "\xAA"
    "n L\xC3"
    "\xAA"
    "n: \xC4"
    "\x90"
    "\xE1"
    "\xBA"
    "\xB7"
    "t l\xE1"
    "\xBA"
    "\xA1"
    "i m\xE1"
    "\xBA"
    "\xB7"
    "c \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8B"
    "nh",
    "N\xC3"
    "\xBA"
    "t b\xC3"
    "\xAA"
    "n Xu\xE1"
    "\xBB"
    "\x91"
    "ng: H\xE1"
    "\xBB"
    "\xA7"
    "y g\xC3"
    "\xA1"
    "n l\xE1"
    "\xBA"
    "\xA1"
    "i",
    "Quay l\xE1"
    "\xBA"
    "\xA1"
    "i (N\xC3"
    "\xBA"
    "t 1)",
    "X\xC3"
    "\xA1"
    "c nh\xE1"
    "\xBA"
    "\xAD"
    "n (N\xC3"
    "\xBA"
    "t 2)",
    "Tr\xC3"
    "\xA1"
    "i (N\xC3"
    "\xBA"
    "t 3)",
    "Ph\xE1"
    "\xBA"
    "\xA3"
    "i (N\xC3"
    "\xBA"
    "t 4)",
    "\xC4"
    "\x90"
    "i t\xE1"
    "\xBB"
    "\x9B"
    "i %",
    "V\xE1"
    "\xBB"
    "\x81"
    " trang ch\xE1"
    "\xBB"
    "\xA7"
    "",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    " ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh",
    "X\xC3"
    "\xB3"
    "a b\xE1"
    "\xBB"
    "\x99"
    " nh\xE1"
    "\xBB"
    "\x9B"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x87"
    "m s\xC3"
    "\xA1"
    "ch",
    "X\xC3"
    "\xB3"
    "a",
    "Hi\xE1"
    "\xBB"
    "\x87"
    "n trang d\xE1"
    "\xBA"
    "\xA1"
    "ng QR",
    "Ch\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng: ",
    " trang  |  ",
    "S\xC3"
    "\xA1"
    "ch: ",
    "shift",
    "SHIFT",
    "KH\xC3"
    "\x93"
    "A",
    "V\xE1"
    "\xBB"
    "\x9B"
    "i Calibre, th\xC3"
    "\xAA"
    "m /opds v\xC3"
    "\xA0"
    "o URL",
    "Tr\xC3"
    "\xA1"
    "i/Ph\xE1"
    "\xBA"
    "\xA3"
    "i: 1%  L\xC3"
    "\xAA"
    "n/Xu\xE1"
    "\xBB"
    "\x91"
    "ng: 10%",
    "\xC4"
    "\x90"
    "ang \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    " gi\xE1"
    "\xBB"
    "\x9D"
    "...",
    "\xC4"
    "\x90"
    "ang t\xC3"
    "\xAD"
    "nh m\xC3"
    "\xA3"
    " b\xC4"
    "\x83"
    "m t\xC3"
    "\xA0"
    "i li\xE1"
    "\xBB"
    "\x87"
    "u...",
    "T\xC3"
    "\xAD"
    "nh m\xC3"
    "\xA3"
    " b\xC4"
    "\x83"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i",
    "\xC4"
    "\x90"
    "ang l\xE1"
    "\xBA"
    "\xA5"
    "y ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh...",
    "\xC4"
    "\x90"
    "ang t\xE1"
    "\xBA"
    "\xA3"
    "i ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh l\xC3"
    "\xAA"
    "n...",
    "Ch\xC6"
    "\xB0"
    "a c\xE1"
    "\xBA"
    "\xA5"
    "u h\xC3"
    "\xAC"
    "nh th\xC3"
    "\xB4"
    "ng tin \xC4"
    "\x91"
    "\xC4"
    "\x83"
    "ng nh\xE1"
    "\xBA"
    "\xAD"
    "p",
    "Thi\xE1"
    "\xBA"
    "\xBF"
    "t l\xE1"
    "\xBA"
    "\xAD"
    "p t\xC3"
    "\xA0"
    "i kho\xE1"
    "\xBA"
    "\xA3"
    "n KOReader trong C\xC3"
    "\xA0"
    "i \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xB7"
    "t",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " t\xC3"
    "\xAC"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "y ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh!",
    "T\xE1"
    "\xBB"
    "\xAB"
    " xa:",
    "C\xE1"
    "\xBB"
    "\xA5"
    "c b\xE1"
    "\xBB"
    "\x99"
    ":",
    "Trang %d, %.2f%% t\xE1"
    "\xBB"
    "\x95"
    "ng",
    "Trang %d/%d, %.2f%% t\xE1"
    "\xBB"
    "\x95"
    "ng",
    "  T\xE1"
    "\xBB"
    "\xAB"
    ": %s",
    "\xC3"
    "\x81"
    "p d\xE1"
    "\xBB"
    "\xA5"
    "ng ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh t\xE1"
    "\xBB"
    "\xAB"
    " xa",
    "T\xE1"
    "\xBA"
    "\xA3"
    "i l\xC3"
    "\xAA"
    "n ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh c\xE1"
    "\xBB"
    "\xA5"
    "c b\xE1"
    "\xBB"
    "\x99"
    "",
    "Kh\xC3"
    "\xB4"
    "ng c\xC3"
    "\xB3"
    " ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh t\xE1"
    "\xBB"
    "\xAB"
    " xa",
    "T\xE1"
    "\xBA"
    "\xA3"
    "i v\xE1"
    "\xBB"
    "\x8B"
    " tr\xC3"
    "\xAD"
    " hi\xE1"
    "\xBB"
    "\x87"
    "n t\xE1"
    "\xBA"
    "\xA1"
    "i l\xC3"
    "\xAA"
    "n?",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " t\xE1"
    "\xBA"
    "\xA3"
    "i ti\xE1"
    "\xBA"
    "\xBF"
    "n tr\xC3"
    "\xAC"
    "nh l\xC3"
    "\xAA"
    "n!",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    " th\xE1"
    "\xBA"
    "\xA5"
    "t b\xE1"
    "\xBA"
    "\xA1"
    "i",
    "Ph\xE1"
    "\xBA"
    "\xA7"
    "n ",
    "T\xE1"
    "\xBA"
    "\xA3"
    "i l\xC3"
    "\xAA"
    "n",
    "Ki\xE1"
    "\xBB"
    "\x83"
    "u c\xE1"
    "\xBB"
    "\xA7"
    "a s\xC3"
    "\xA1"
    "ch",
    "Ki\xE1"
    "\xBB"
    "\x83"
    "u nh\xC3"
    "\xBA"
    "ng",
    "URL m\xC3"
    "\xA1"
    "y ch\xE1"
    "\xBB"
    "\xA7"
    " OPDS",
    "Ch\xC3"
    "\xBA"
    " th\xC3"
    "\xAD"
    "ch",
    "Kh\xC3"
    "\xB4"
    "ng c\xC3"
    "\xB3"
    " ch\xC3"
    "\xBA"
    " th\xC3"
    "\xAD"
    "ch tr\xC3"
    "\xAA"
    "n trang n\xC3"
    "\xA0"
    "y",
    "[li\xC3"
    "\xAA"
    "n k\xE1"
    "\xBA"
    "\xBF"
    "t]",
    "Ch\xE1"
    "\xBB"
    "\xA5"
    "p m\xC3"
    "\xA0"
    "n h\xC3"
    "\xAC"
    "nh",
    "T\xE1"
    "\xBB"
    "\xB1"
    " L\xE1"
    "\xBA"
    "\xAD"
    "t Trang: ",
    "T\xE1"
    "\xBB"
    "\xB1"
    " L\xE1"
    "\xBA"
    "\xAD"
    "t (Trang/Ph\xC3"
    "\xBA"
    "t)",
    "T\xE1"
    "\xBB"
    "\xB1"
    " L\xE1"
    "\xBA"
    "\xAD"
    "t Trang",
    "1 trang/ph\xC3"
    "\xBA"
    "t",
    "3 trang/ph\xC3"
    "\xBA"
    "t",
    "6 trang/ph\xC3"
    "\xBA"
    "t",
    "12 trang/ph\xC3"
    "\xBA"
    "t",
    "\xE1"
    "\xBB"
    "\xA8"
    "ng d\xE1"
    "\xBB"
    "\xA5"
    "ng",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x93"
    "ng h\xE1"
    "\xBB"
    "\x93"
    "",
    "Pomodoro",
    "Tr\xC3"
    "\xAD"
    "ch d\xE1"
    "\xBA"
    "\xAB"
    "n h\xC3"
    "\xA0"
    "ng ng\xC3"
    "\xA0"
    "y",
    "K\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i WiFi \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x83"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    " gi\xE1"
    "\xBB"
    "\x9D"
    "",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBA"
    "\xB7"
    "t quotes.txt v\xC3"
    "\xA0"
    "o th\xE1"
    "\xBA"
    "\xBB"
    " SD",
    "(Tr\xC3"
    "\xAD"
    "ch d\xE1"
    "\xBA"
    "\xAB"
    "n m\xE1"
    "\xBA"
    "\xB7"
    "c \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8B"
    "nh)",
    "S\xE1"
    "\xBA"
    "\xB4"
    "N S\xC3"
    "\x80"
    "NG",
    "T\xE1"
    "\xBA"
    "\xAC"
    "P TRUNG",
    "NGH\xE1"
    "\xBB"
    "\x88"
    " NG\xE1"
    "\xBA"
    "\xAE"
    "N",
    "NGH\xE1"
    "\xBB"
    "\x88"
    " D\xC3"
    "\x80"
    "I",
    "T\xE1"
    "\xBA"
    "\xA0"
    "M D\xE1"
    "\xBB"
    "\xAA"
    "NG",
    "B\xE1"
    "\xBA"
    "\xAF"
    "t \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xA7"
    "u",
    "T\xE1"
    "\xBA"
    "\xA1"
    "m d\xE1"
    "\xBB"
    "\xAB"
    "ng",
    "Ti\xE1"
    "\xBA"
    "\xBF"
    "p t\xE1"
    "\xBB"
    "\xA5"
    "c",
    "B\xE1"
    "\xBB"
    "\x8F"
    " qua",
    "\xC4"
    "\x90"
    "i\xE1"
    "\xBB"
    "\x81"
    "u khi\xE1"
    "\xBB"
    "\x83"
    "n Bluetooth",
    "T\xE1"
    "\xBB"
    "\xB1"
    " k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i BT",
    "Gh\xC3"
    "\xA9"
    "p n\xE1"
    "\xBB"
    "\x91"
    "i",
    "\xC4"
    "\x90"
    "ang qu\xC3"
    "\xA9"
    "t...",
    "\xC4"
    "\x90"
    "ang k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i...",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i",
    "Ch\xC6"
    "\xB0"
    "a k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i",
    "Kh\xC3"
    "\xB4"
    "ng t\xC3"
    "\xAC"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "y thi\xE1"
    "\xBA"
    "\xBF"
    "t b\xE1"
    "\xBB"
    "\x8B"
    "",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " gh\xC3"
    "\xA9"
    "p: %s",
    "Qu\xC3"
    "\xAA"
    "n thi\xE1"
    "\xBA"
    "\xBF"
    "t b\xE1"
    "\xBB"
    "\x8B"
    "",
    "Qu\xC3"
    "\xAA"
    "n \xC4"
    "\x91"
    "i\xE1"
    "\xBB"
    "\x81"
    "u khi\xE1"
    "\xBB"
    "\x83"
    "n \xC4"
    "\x91"
    "\xC3"
    "\xA3"
    " gh\xC3"
    "\xA9"
    "p?",
    "Learn Keys",
    "Press NEXT on remote",
    "Press PREV on remote",
    "Keys learned!",
    "B\xC3"
    "\xBA"
    "t tr\xC3"
    "\xAC"
    "nh chi\xE1"
    "\xBA"
    "\xBF"
    "u",
    "\xC4"
    "\x90"
    "ang ch\xE1"
    "\xBB"
    "\x9D"
    " k\xE1"
    "\xBA"
    "\xBF"
    "t n\xE1"
    "\xBB"
    "\x91"
    "i...",
    "Gh\xC3"
    "\xA9"
    "p thi\xE1"
    "\xBA"
    "\xBF"
    "t b\xE1"
    "\xBB"
    "\x8B"
    " nh\xC6"
    "\xB0"
    " b\xC3"
    "\xA0"
    "n ph\xC3"
    "\xAD"
    "m Bluetooth",
    "Ph\xE1"
    "\xBA"
    "\xA3"
    "i ->",
    "Slide ti\xE1"
    "\xBA"
    "\xBF"
    "p",
    "<- Tr\xC3"
    "\xA1"
    "i",
    "Slide tr\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c",
    "OK",
    "B\xE1"
    "\xBA"
    "\xAF"
    "t \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xA7"
    "u (F5)",
    "Quay l\xE1"
    "\xBA"
    "\xA1"
    "i",
    "K\xE1"
    "\xBA"
    "\xBF"
    "t th\xC3"
    "\xBA"
    "c (Esc)",
    "Ti\xE1"
    "\xBA"
    "\xBF"
    "p >",
    "< Tr\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c",
    "F5",
    "Esc",
    "G\xC3"
    "\xA0"
    " \xE1"
    "\xBA"
    "\xA2"
    "o",
    "No",
    "Vui",
    "S\xE1"
    "\xBB"
    "\xA9"
    "c Kh\xE1"
    "\xBB"
    "\x8F"
    "e",
    "Tr\xE1"
    "\xBB"
    "\xA9"
    "ng",
    "M\xE1"
    "\xBB"
    "\x9B"
    "i N\xE1"
    "\xBB"
    "\x9F"
    "",
    "Nh\xE1"
    "\xBB"
    "\x8F"
    "",
    "Tr\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9F"
    "ng Th\xC3"
    "\xA0"
    "nh",
    "Gi\xC3"
    "\xA0"
    "",
    "Th\xC3"
    "\xBA"
    " c\xC6"
    "\xB0"
    "ng \xC4"
    "\x91"
    "\xC3"
    "\xA3"
    " qua \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x9D"
    "i...",
    "\xE1"
    "\xBA"
    "\xA4"
    "p Tr\xE1"
    "\xBB"
    "\xA9"
    "ng M\xE1"
    "\xBB"
    "\x9B"
    "i?",
    "Ch\xC6"
    "\xB0"
    "a c\xC3"
    "\xB3"
    " th\xC3"
    "\xBA"
    " c\xC6"
    "\xB0"
    "ng",
    "\xE1"
    "\xBA"
    "\xA4"
    "p Tr\xE1"
    "\xBB"
    "\xA9"
    "ng?",
    "C\xC3"
    "\xA2"
    "n N\xE1"
    "\xBA"
    "\xB7"
    "ng",
    "K\xE1"
    "\xBB"
    "\xB7"
    " Lu\xE1"
    "\xBA"
    "\xAD"
    "t",
    "L\xE1"
    "\xBB"
    "\x97"
    "i",
    "Ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "B\xE1"
    "\xBB"
    "\x87"
    "nh",
    "B\xE1"
    "\xBA"
    "\xA9"
    "n",
    "C\xE1"
    "\xBA"
    "\xA7"
    "n ch\xC3"
    "\xBA"
    " \xC3"
    "\xBD"
    "!",
    "Nh\xC3"
    "\xB3"
    "c Ch\xC4"
    "\x83"
    "m",
    "Nh\xC3"
    "\xB3"
    "c Ngh\xE1"
    "\xBB"
    "\x8B"
    "ch",
    "H\xE1"
    "\xBB"
    "\x8D"
    "c Gi\xE1"
    "\xBA"
    "\xA3"
    "",
    "B\xE1"
    "\xBA"
    "\xA1"
    "n Ngh\xE1"
    "\xBB"
    "\x8B"
    "ch",
    "Ngon qu\xC3"
    "\xA1"
    "! +\xC4"
    "\x90"
    "\xC3"
    "\xB3"
    "i",
    "Yummy! +Vui",
    "Kh\xE1"
    "\xBB"
    "\x8F"
    "e h\xC6"
    "\xA1"
    "n r\xE1"
    "\xBB"
    "\x93"
    "i~",
    "T\xE1"
    "\xBA"
    "\xAD"
    "p xong!",
    "S\xE1"
    "\xBA"
    "\xA1"
    "ch r\xE1"
    "\xBB"
    "\x93"
    "i!",
    "K\xE1"
    "\xBB"
    "\xB7"
    " lu\xE1"
    "\xBA"
    "\xAD"
    "t t\xE1"
    "\xBB"
    "\x91"
    "t!",
    "\xC3"
    "\x81"
    "c qu\xC3"
    "\xA1"
    "...",
    "T\xE1"
    "\xBB"
    "\x91"
    "t l\xE1"
    "\xBA"
    "\xAF"
    "m!",
    "T\xE1"
    "\xBB"
    "\xA7"
    "i l\xC3"
    "\xB2"
    "ng...",
    "Ng\xE1"
    "\xBB"
    "\xA7"
    " ngon~",
    "B\xE1"
    "\xBA"
    "\xAD"
    "t \xC4"
    "\x91"
    "\xC3"
    "\xA8"
    "n!",
    "Th\xC3"
    "\xBA"
    " c\xC6"
    "\xB0"
    "ng \xC4"
    "\x91"
    "\xC3"
    "\xA3"
    " s\xE1"
    "\xBB"
    "\x91"
    "ng tr\xE1"
    "\xBB"
    "\x8D"
    "n v\xE1"
    "\xBA"
    "\xB9"
    "n. T\xE1"
    "\xBA"
    "\xA1"
    "m bi\xE1"
    "\xBB"
    "\x87"
    "t~",
    "Th\xC3"
    "\xBA"
    " c\xC6"
    "\xB0"
    "ng \xC4"
    "\x91"
    "\xC3"
    "\xA3"
    " m\xE1"
    "\xBA"
    "\xA5"
    "t v\xC3"
    "\xAC"
    " b\xE1"
    "\xBB"
    "\x8B"
    " b\xE1"
    "\xBB"
    "\x8F"
    " b\xC3"
    "\xAA"
    "...",
    "B\xE1"
    "\xBB"
    "\x87"
    "nh qu\xC3"
    "\xA1"
    " kh\xC3"
    "\xB4"
    "ng \xC4"
    "\x83"
    "n \xC4"
    "\x91"
    "\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "c...",
    "Su\xE1"
    "\xBB"
    "\xB5"
    "t... \xC4"
    "\x91"
    "ang ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "Ch\xC6"
    "\xB0"
    "a s\xE1"
    "\xBA"
    "\xB5"
    "n s\xC3"
    "\xA0"
    "ng...",
    "Cho \xC4"
    "\x82"
    "n",
    "Cho \xC4"
    "\x82"
    "n V\xE1"
    "\xBA"
    "\xB7"
    "t",
    "U\xE1"
    "\xBB"
    "\x91"
    "ng Thu\xE1"
    "\xBB"
    "\x91"
    "c",
    "T\xE1"
    "\xBA"
    "\xAD"
    "p Th\xE1"
    "\xBB"
    "\x83"
    " D\xE1"
    "\xBB"
    "\xA5"
    "c",
    "D\xE1"
    "\xBB"
    "\x8D"
    "n D\xE1"
    "\xBA"
    "\xB9"
    "p",
    "M\xE1"
    "\xBA"
    "\xAF"
    "ng",
    "B\xE1"
    "\xBB"
    "\x8F"
    " Qua",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA8"
    "n",
    "Vu\xE1"
    "\xBB"
    "\x91"
    "t Ve",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x95"
    "i T\xC3"
    "\xAA"
    "n",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x95"
    "i Lo\xE1"
    "\xBA"
    "\xA1"
    "i",
    "T\xC3"
    "\xAA"
    "n Th\xC3"
    "\xBA"
    " C\xC6"
    "\xB0"
    "ng",
    "Ch\xE1"
    "\xBB"
    "\x8D"
    "n Lo\xE1"
    "\xBA"
    "\xA1"
    "i Th\xC3"
    "\xBA"
    " C\xC6"
    "\xB0"
    "ng",
    "G\xC3"
    "\xA0"
    "",
    "M\xC3"
    "\xA8"
    "o",
    "Ch\xC3"
    "\xB3"
    "",
    "R\xE1"
    "\xBB"
    "\x93"
    "ng",
    "Th\xE1"
    "\xBB"
    "\x8F"
    "",
    "Robot",
    "G\xE1"
    "\xBA"
    "\xA5"
    "u",
    "Slime",
    "Ho\xC3"
    "\xA0"
    "n th\xC3"
    "\xA0"
    "nh ch\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng!",
    "%un",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBA"
    "\xA1"
    "t m\xE1"
    "\xBB"
    "\xA5"
    "c ti\xC3"
    "\xAA"
    "u h\xC3"
    "\xB4"
    "m nay!",
    "Chu\xE1"
    "\xBB"
    "\x97"
    "i t\xC4"
    "\x83"
    "ng! %u ng\xC3"
    "\xA0"
    "y",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c %lu trang!",
    "%s: Cho \xC4"
    "\x83"
    "n \xC4"
    "\x91"
    "i! \xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8D"
    "c th\xC3"
    "\xAA"
    "m n\xC3"
    "\xA0"
    "o",
    "%s: Nh\xE1"
    "\xBB"
    "\x9B"
    " b\xE1"
    "\xBA"
    "\xA1"
    "n qu\xC3"
    "\xA1"
    "...",
    "%s: M\xC3"
    "\xAC"
    "nh b\xE1"
    "\xBB"
    "\x8B"
    " \xE1"
    "\xBB"
    "\x91"
    "m...",
    "%s: Ch\xC6"
    "\xA1"
    "i v\xE1"
    "\xBB"
    "\x9B"
    "i m\xC3"
    "\xAC"
    "nh!",
    "%s: Zzz...",
    "%s: Chu\xE1"
    "\xBB"
    "\x97"
    "i %u ng\xC3"
    "\xA0"
    "y!",
    "%s: \xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8D"
    "c s\xC3"
    "\xA1"
    "ch n\xC3"
    "\xA0"
    "o!",
    "%s: \xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8D"
    "c c\xC3"
    "\xB9"
    "ng m\xC3"
    "\xAC"
    "nh~",
    "Kh\xC3"
    "\xB4"
    "ng c\xC3"
    "\xB3"
    " th\xC3"
    "\xBA"
    "!",
    "Kh\xC3"
    "\xB4"
    "ng b\xE1"
    "\xBB"
    "\x87"
    "nh!",
    "S\xE1"
    "\xBA"
    "\xA1"
    "ch r\xE1"
    "\xBB"
    "\x93"
    "i!",
    "B\xE1"
    "\xBB"
    "\x87"
    "nh kh\xC3"
    "\xB4"
    "ng t\xE1"
    "\xBA"
    "\xAD"
    "p \xC4"
    "\x91"
    "\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "c",
    "Kh\xC3"
    "\xB4"
    "ng c\xC3"
    "\xB3"
    " g\xC3"
    "\xAC"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x83"
    " b\xE1"
    "\xBB"
    "\x8F"
    " qua",
    "\xC3"
    "\x8A"
    "! Kh\xC3"
    "\xB4"
    "ng c\xC3"
    "\xB4"
    "ng b\xE1"
    "\xBA"
    "\xB1"
    "ng...",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8D"
    "c 20 trang",
    "Vu\xE1"
    "\xBB"
    "\x91"
    "t ve 3 l\xE1"
    "\xBA"
    "\xA7"
    "n",
    "No b\xE1"
    "\xBB"
    "\xA5"
    "ng (>40%)",
    "%s (%s)  |  Ng\xC3"
    "\xA0"
    "y %lu  |  Chu\xE1"
    "\xBB"
    "\x97"
    "i %u",
    "%s %s  |  Ng\xC3"
    "\xA0"
    "y %lu  |  Chu\xE1"
    "\xBB"
    "\x97"
    "i %u",
    "%s  |  Ng\xC3"
    "\xA0"
    "y %lu  |  Chu\xE1"
    "\xBB"
    "\x97"
    "i %u",
    "Khung \xE1"
    "\xBA"
    "\xA2"
    "nh",
    "M\xC3"
    "\xAA"
    " Cung",
    "Tr\xC3"
    "\xB2"
    " Ch\xC6"
    "\xA1"
    "i Cu\xE1"
    "\xBB"
    "\x99"
    "c S\xE1"
    "\xBB"
    "\x91"
    "ng",
    "M\xC3"
    "\xAA"
    " Cung M\xE1"
    "\xBB"
    "\x9B"
    "i",
    "R\xE1"
    "\xBA"
    "\xAF"
    "n",
    "2048",
    "Ch\xC6"
    "\xA1"
    "i l\xE1"
    "\xBA"
    "\xA1"
    "i",
    "Th\xE1"
    "\xBB"
    "\x91"
    "ng K\xC3"
    "\xAA"
    " \xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8D"
    "c",
    "H\xC3"
    "\x94"
    "M NAY",
    "T\xE1"
    "\xBB"
    "\x94"
    "NG",
    "S\xC3"
    "\x81"
    "CH G\xE1"
    "\xBA"
    "\xA6"
    "N NH\xE1"
    "\xBA"
    "\xA4"
    "T",
    "Phi\xC3"
    "\xAA"
    "n \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c",
    "Ho\xC3"
    "\xA0"
    "n th\xC3"
    "\xA0"
    "nh",
    "Chu\xE1"
    "\xBB"
    "\x97"
    "i ng\xC3"
    "\xA0"
    "y",
    "K\xE1"
    "\xBB"
    "\xB7"
    " l\xE1"
    "\xBB"
    "\xA5"
    "c",
    "%u ng\xC3"
    "\xA0"
    "y",
    "Ch\xC6"
    "\xB0"
    "a \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c s\xC3"
    "\xA1"
    "ch n\xC3"
    "\xA0"
    "o",
    "Thua r\xE1"
    "\xBB"
    "\x93"
    "i!",
    "Th\xE1"
    "\xBA"
    "\xAF"
    "ng r\xE1"
    "\xBB"
    "\x93"
    "i!",
    "\xC4"
    "\x90"
    "i\xE1"
    "\xBB"
    "\x83"
    "m: %lu    Cao: %lu",
    "\xC4"
    "\x90"
    "i\xE1"
    "\xBB"
    "\x83"
    "m:%d Cao:%d",
    "L\xC3"
    "\xAA"
    "n/Xu\xE1"
    "\xBB"
    "\x91"
    "ng: t\xE1"
    "\xBB"
    "\x91"
    "c \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x99"
    "",
    "Xong! %d b\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c",
    "B\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\x9B"
    "c: %d",
    "Th\xE1"
    "\xBA"
    "\xBF"
    " h\xE1"
    "\xBB"
    "\x87"
    " %lu",
    "L\xE1"
    "\xBB"
    "\x97"
    "i: %d",
    "Kh\xC3"
    "\xB4"
    "ng t\xC3"
    "\xAC"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "y \xE1"
    "\xBA"
    "\xA3"
    "nh",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBA"
    "\xB7"
    "t file .bmp v\xC3"
    "\xA0"
    "o /sleep/",
    "Vui",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8D"
    "c s\xC3"
    "\xA1"
    "ch",
    "Cho \xC4"
    "\x83"
    "n \xC4"
    "\x91"
    "i~",
    "C\xE1"
    "\xBA"
    "\xA7"
    "n thu\xE1"
    "\xBB"
    "\x91"
    "c...",
    "B\xE1"
    "\xBA"
    "\xA9"
    "n qu\xC3"
    "\xA1"
    "...",
    "Ch\xC3"
    "\xA1"
    "n qu\xC3"
    "\xA1"
    "...",
    "N\xC3"
    "\xA0"
    "y!",
    "Kh\xC3"
    "\xB4"
    "ng kh\xE1"
    "\xBB"
    "\x8F"
    "e...",
    "Zzz...",
    "Purr~",
    "Ng\xE1"
    "\xBB"
    "\xA7"
    " ngon",
    "\xC4"
    "\x90"
    "ang m\xC6"
    "\xA1"
    "...",
    "\xC4"
    "\x90"
    "\xC3"
    "\xB3"
    "i b\xE1"
    "\xBB"
    "\xA5"
    "ng...",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8D"
    "c th\xC3"
    "\xAA"
    "m n\xC3"
    "\xA0"
    "o!",
    "%s | %d s\xE1"
    "\xBB"
    "\x91"
    "ng",
    "Nhanh",
    "V\xE1"
    "\xBB"
    "\xAB"
    "a",
    "Ch\xE1"
    "\xBA"
    "\xAD"
    "m",
    "R\xE1"
    "\xBA"
    "\xA5"
    "t ch\xE1"
    "\xBA"
    "\xAD"
    "m",
    "Sudoku",
    "D\xE1"
    "\xBB"
    "\x85"
    "",
    "Trung b\xC3"
    "\xAC"
    "nh",
    "Kh\xC3"
    "\xB3"
    "",
    "Ho\xC3"
    "\xA0"
    "n th\xC3"
    "\xA0"
    "nh!",
    "1-9",
    "D\xC3"
    "\xB2"
    " m\xC3"
    "\xAC"
    "n",
    "D\xE1"
    "\xBB"
    "\x85"
    "",
    "Trung b\xC3"
    "\xAC"
    "nh",
    "Kh\xC3"
    "\xB3"
    "",
    "M\xC3"
    "\xAC"
    "n: %d",
    "M\xE1"
    "\xBB"
    "\x9F"
    "",
    "C\xE1"
    "\xBB"
    "\x9D"
    "",
    "Caro",
    "L\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "t: X",
    "L\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "t: O",
    "X th\xE1"
    "\xBA"
    "\xAF"
    "ng!",
    "O th\xE1"
    "\xBA"
    "\xAF"
    "ng!",
    "H\xC3"
    "\xB2"
    "a!",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBA"
    "\xB7"
    "t",
    "D\xE1"
    "\xBB"
    "\x85"
    "",
    "Trung b\xC3"
    "\xAC"
    "nh",
    "Kh\xC3"
    "\xB3"
    "",
    "Ch\xE1"
    "\xBB"
    "\x8D"
    "n \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x99"
    " kh\xC3"
    "\xB3"
    "",
    "C\xE1"
    "\xBB"
    "\x9D"
    " vua",
    "L\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "t Tr\xE1"
    "\xBA"
    "\xAF"
    "ng",
    "L\xC6"
    "\xB0"
    "\xE1"
    "\xBB"
    "\xA3"
    "t \xC4"
    "\x90"
    "en",
    "Tr\xE1"
    "\xBA"
    "\xAF"
    "ng th\xE1"
    "\xBA"
    "\xAF"
    "ng!",
    "\xC4"
    "\x90"
    "en th\xE1"
    "\xBA"
    "\xAF"
    "ng!",
    "Ch\xE1"
    "\xBB"
    "\x8D"
    "n",
    "\xC4"
    "\x90"
    "i",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBA"
    "\xB7"
    "t Gi\xE1"
    "\xBB"
    "\x9D"
    "",
    "Ch\xE1"
    "\xBB"
    "\xA7"
    " Nh\xE1"
    "\xBA"
    "\xAD"
    "t",
    "Th\xE1"
    "\xBB"
    "\xA9"
    " Hai",
    "Th\xE1"
    "\xBB"
    "\xA9"
    " Ba",
    "Th\xE1"
    "\xBB"
    "\xA9"
    " T\xC6"
    "\xB0"
    "",
    "Th\xE1"
    "\xBB"
    "\xA9"
    " N\xC4"
    "\x83"
    "m",
    "Th\xE1"
    "\xBB"
    "\xA9"
    " S\xC3"
    "\xA1"
    "u",
    "Th\xE1"
    "\xBB"
    "\xA9"
    " B\xE1"
    "\xBA"
    "\xA3"
    "y",
    "CN",
    "T2",
    "T3",
    "T4",
    "T5",
    "T6",
    "T7",
    "\xC3"
    "\x82"
    "m l\xE1"
    "\xBB"
    "\x8B"
    "ch",
    "Th\xC3"
    "\xA1"
    "ng 1",
    "Th\xC3"
    "\xA1"
    "ng 2",
    "Th\xC3"
    "\xA1"
    "ng 3",
    "Th\xC3"
    "\xA1"
    "ng 4",
    "Th\xC3"
    "\xA1"
    "ng 5",
    "Th\xC3"
    "\xA1"
    "ng 6",
    "Th\xC3"
    "\xA1"
    "ng 7",
    "Th\xC3"
    "\xA1"
    "ng 8",
    "Th\xC3"
    "\xA1"
    "ng 9",
    "Th\xC3"
    "\xA1"
    "ng 10",
    "Th\xC3"
    "\xA1"
    "ng 11",
    "Th\xC3"
    "\xA1"
    "ng 12",
    "Gi\xE1"
    "\xBB"
    "\x9D"
    "",
    "Ph\xC3"
    "\xBA"
    "t",
    "Ng\xC3"
    "\xA0"
    "y",
    "Th\xC3"
    "\xA1"
    "ng",
    "N\xC4"
    "\x83"
    "m",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    " gi\xE1"
    "\xBB"
    "\x9D"
    " qua WiFi",
    "Th\xE1"
    "\xBB"
    "\x9D"
    "i ti\xE1"
    "\xBA"
    "\xBF"
    "t",
    "\xC4"
    "\x90"
    "ang t\xE1"
    "\xBA"
    "\xA3"
    "i th\xE1"
    "\xBB"
    "\x9D"
    "i ti\xE1"
    "\xBA"
    "\xBF"
    "t...",
    "Temperature",
    "\xC2"
    "\xB0"
    "C",
    "\xC2"
    "\xB0"
    "F",
    "Kh\xC3"
    "\xB4"
    "ng th\xE1"
    "\xBB"
    "\x83"
    " t\xE1"
    "\xBA"
    "\xA3"
    "i th\xE1"
    "\xBB"
    "\x9D"
    "i ti\xE1"
    "\xBA"
    "\xBF"
    "t",
    "C\xE1"
    "\xBA"
    "\xA3"
    "m gi\xC3"
    "\xA1"
    "c nh\xC6"
    "\xB0"
    "",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x99"
    " \xE1"
    "\xBA"
    "\xA9"
    "m",
    "Gi\xC3"
    "\xB3"
    "",
    "L\xC3"
    "\xA0"
    "m m\xE1"
    "\xBB"
    "\x9B"
    "i",
    "Th\xC3"
    "\xA0"
    "nh ph\xE1"
    "\xBB"
    "\x91"
    "",
    "Tr\xE1"
    "\xBB"
    "\x9D"
    "i quang",
    "C\xC3"
    "\xB3"
    " m\xC3"
    "\xA2"
    "y",
    "S\xC6"
    "\xB0"
    "\xC6"
    "\xA1"
    "ng m\xC3"
    "\xB9"
    "",
    "M\xC6"
    "\xB0"
    "a ph\xC3"
    "\xB9"
    "n",
    "M\xC6"
    "\xB0"
    "a",
    "Tuy\xE1"
    "\xBA"
    "\xBF"
    "t",
    "M\xC6"
    "\xB0"
    "a r\xC3"
    "\xA0"
    "o",
    "Gi\xC3"
    "\xB4"
    "ng",
    "C\xE1"
    "\xBA"
    "\xAD"
    "p nh\xE1"
    "\xBA"
    "\xAD"
    "t",
    "T\xE1"
    "\xBA"
    "\xAD"
    "p trung:",
    "Ngh\xE1"
    "\xBB"
    "\x89"
    " ng\xE1"
    "\xBA"
    "\xAF"
    "n:",
    "Ngh\xE1"
    "\xBB"
    "\x89"
    " d\xC3"
    "\xA0"
    "i:",
    "%s %2lu ph\xC3"
    "\xBA"
    "t",
    "B\xE1"
    "\xBA"
    "\xAF"
    "t \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xA7"
    "u >",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8B"
    "a \xC4"
    "\x91"
    "i\xE1"
    "\xBB"
    "\x83"
    "m",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x93"
    "ng h\xE1"
    "\xBB"
    "\x93"
    " trang ch\xE1"
    "\xBB"
    "\xA7"
    "",
    "Th\xE1"
    "\xBB"
    "\x9D"
    "i ti\xE1"
    "\xBA"
    "\xBF"
    "t trang ch\xE1"
    "\xBB"
    "\xA7"
    "",
    "Tr\xE1"
    "\xBA"
    "\xA1"
    "ng th\xC3"
    "\xA1"
    "i th\xC3"
    "\xBA"
    " c\xC6"
    "\xB0"
    "ng",
    "Th\xE1"
    "\xBB"
    "\x91"
    "ng k\xC3"
    "\xAA"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c s\xC3"
    "\xA1"
    "ch",
    "\xC4"
    "\x90"
    "\xC3"
    "\x83"
    " \xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8C"
    "C",
    "H\xC3"
    "\xB4"
    "m nay",
    "T\xE1"
    "\xBB"
    "\x95"
    "ng",
    "L\xE1"
    "\xBA"
    "\xA7"
    "n \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x8D"
    "c",
    "\xC4"
    "\x90"
    "\xC3"
    "\x83"
    " \xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x8C"
    "C",
    "%d l\xE1"
    "\xBA"
    "\xA7"
    "n",
    "%d ph\xC3"
    "\xBA"
    "t",
    "%dh %dp",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    "",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " \xC4"
    "\x91"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    "",
    "WiFi qu\xC3"
    "\xA1"
    " h\xE1"
    "\xBA"
    "\xA1"
    "n",
    "L\xE1"
    "\xBB"
    "\x97"
    "i API %d",
    "\xE1"
    "\xBA"
    "\xA2"
    "nh m\xC3"
    "\xA0"
    "n h\xC3"
    "\xAC"
    "nh ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " ch\xE1"
    "\xBB"
    "\x8D"
    "n \xE1"
    "\xBA"
    "\xA3"
    "nh!",
    "Kh\xC3"
    "\xB4"
    "ng t\xC3"
    "\xAC"
    "m th\xE1"
    "\xBA"
    "\xA5"
    "y file .bmp",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBA"
    "\xB7"
    "t file .bmp v\xC3"
    "\xA0"
    "o th\xC6"
    "\xB0"
    " m\xE1"
    "\xBB"
    "\xA5"
    "c /sleep/",
    "Ng\xE1"
    "\xBA"
    "\xAB"
    "u nhi\xC3"
    "\xAA"
    "n",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBA"
    "\xB7"
    "t m\xC3"
    "\xA0"
    "n h\xC3"
    "\xAC"
    "nh ng\xE1"
    "\xBB"
    "\xA7"
    " th\xC3"
    "\xA0"
    "nh 'T\xC3"
    "\xB9"
    "y ch\xE1"
    "\xBB"
    "\x89"
    "nh' trong C\xC3"
    "\xA0"
    "i \xC4"
    "\x91"
    "\xE1"
    "\xBA"
    "\xB7"
    "t > Hi\xE1"
    "\xBB"
    "\x83"
    "n th\xE1"
    "\xBB"
    "\x8B"
    "",
    "Starred Pages",
    "Star Page",
    "No starred pages",
    "p",
    "Page starred",
    "Page unstarred",
    "X\xC3"
    "\xB3"
    "a cache m\xC3"
    "\xA0"
    "n h\xC3"
    "\xAC"
    "nh ng\xE1"
    "\xBB"
    "\xA7"
    "",
    "\xC4"
    "\x90"
    "\xC3"
    "\xA3"
    " x\xC3"
    "\xB3"
    "a cache m\xC3"
    "\xA0"
    "n h\xC3"
    "\xAC"
    "nh ng\xE1"
    "\xBB"
    "\xA7"
    "!",
    "\xC4"
    "\x90"
    "\xE1"
    "\xBB"
    "\x93"
    "ng b\xE1"
    "\xBB"
    "\x99"
    " th\xE1"
    "\xBB"
    "\x9D"
    "i ti\xE1"
    "\xBA"
    "\xBF"
    "t & gi\xE1"
    "\xBB"
    "\x9D"
    "",
    "N\xC3"
    "\xBA"
    "t ngu\xE1"
    "\xBB"
    "\x93"
    "n b\xE1"
    "\xBA"
    "\xA5"
    "m \xC4"
    "\x91"
    "\xC3"
    "\xB4"
    "i",
    "N\xC3"
    "\xBA"
    "t ngu\xE1"
    "\xBB"
    "\x93"
    "n b\xE1"
    "\xBA"
    "\xA5"
    "m ba",
    "Hi\xE1"
    "\xBB"
    "\x83"
    "n th\xE1"
    "\xBB"
    "\x8B"
    " RAM",
};

}  // namespace i18n_strings

// Compile-time validation of array sizes
static_assert(sizeof(i18n_strings::STRINGS_EN) / sizeof(i18n_strings::STRINGS_EN[0]) ==
                  static_cast<size_t>(StrId::_COUNT),
              "STRINGS_EN size mismatch");
static_assert(sizeof(i18n_strings::STRINGS_VI) / sizeof(i18n_strings::STRINGS_VI[0]) ==
                  static_cast<size_t>(StrId::_COUNT),
              "STRINGS_VI size mismatch");
