#pragma once

#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_bolditalic.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_bolditalic.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_bolditalic.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/lexend_12_bold.h>
#include <builtinFonts/lexend_12_regular.h>
#include <builtinFonts/lexend_14_bold.h>
#include <builtinFonts/lexend_14_regular.h>
#include <builtinFonts/lexend_16_bold.h>
#include <builtinFonts/lexend_16_regular.h>
#include <builtinFonts/lexend_18_bold.h>
#include <builtinFonts/lexend_18_regular.h>
#include <builtinFonts/bokerlam_12_bold.h>
#include <builtinFonts/bokerlam_12_italic.h>
#include <builtinFonts/bokerlam_12_regular.h>
#include <builtinFonts/bokerlam_14_bold.h>
#include <builtinFonts/bokerlam_14_italic.h>
#include <builtinFonts/bokerlam_14_regular.h>
#include <builtinFonts/bokerlam_16_bold.h>
#include <builtinFonts/bokerlam_16_italic.h>
#include <builtinFonts/bokerlam_16_regular.h>
#include <builtinFonts/bokerlam_18_bold.h>
#include <builtinFonts/bokerlam_18_italic.h>
#include <builtinFonts/bokerlam_18_regular.h>
