#pragma once
#include <cstdint>

// Bluetooth icon 12x12 — classic "ᛒ" rune shape
// 1-bit bitmap: 0 = black (drawn), 1 = white (transparent)
// 2 bytes per row, MSB first, 12 pixels used + 4 padding bits
//
// Pixel art (# = black):
//   ....#.......
//   ....##......
//   .#..#.#.....
//   ..#.#..#....
//   ...##..#....
//   ....#.#.....
//   ....#.#.....
//   ...##..#....
//   ..#.#..#....
//   .#..#.#.....
//   ....##......
//   ....#.......
static const uint8_t BluetoothIcon12[] = {
    0xF7, 0xF0,  // ....#.......
    0xF3, 0xF0,  // ....##......
    0xD7, 0x70,  // .#..#.#.....
    0xEB, 0x30,  // ..#.#..#....
    0xF3, 0x30,  // ...##..#....
    0xF5, 0x70,  // ....#.#.....
    0xF5, 0x70,  // ....#.#.....
    0xF3, 0x30,  // ...##..#....
    0xEB, 0x30,  // ..#.#..#....
    0xD7, 0x70,  // .#..#.#.....
    0xF3, 0xF0,  // ....##......
    0xF7, 0xF0,  // ....#.......
};
